Repository responsible-ai-collaborative/aiid, pull requests merged in 2022-10, with the labels that each got.

#1169 Entities improvements
  site/gatsby-site/src/components/entities/CommonEntities.js
  site/gatsby-site/src/components/entities/EntityCard.js
  site/gatsby-site/src/components/incidents/IncidentCard.js
  site/gatsby-site/src/templates/entity.js
Labels: PR:Mergeable

#1192 Document `SKIP_PAGE_CREATOR`
  README.md
Labels: PR:Needs Review

#1164 Plot of incident growth
  site/gatsby-site/src/components/visualizations/MultiLineChart.js
  site/gatsby-site/src/pages/summaries/incidentsOverTime.js
Labels: PR:Needs Review

#1027 Add links to toasts, use tailwind colors
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/SemanticallyRelatedIncidents.js
  site/gatsby-site/src/components/incidents/IncidentEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/contexts/ToastContext.js
  site/gatsby-site/src/hooks/useToast.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/pages/incidents/edit.js
Labels: PR:Needs Review

#1198 Add description to citation page
  site/gatsby-site/page-creators/createCitationPages.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1194 Add canonical url and image to landing page
  site/gatsby-site/src/templates/landingPage.js
Labels: PR:Needs Review

#1197 Hide description when incident id is set, make fields optional
  site/gatsby-site/src/components/submissions/SubmissionForm.js
Labels: PR:Needs Review

#1184 Move SubmissionList inside main wrapper
  site/gatsby-site/src/pages/apps/submitted.js
Labels: PR:Needs Review

#1199 Split “Welcome to the” / “AI Incident Database”
  site/gatsby-site/i18n/locales/es/landing.json
  site/gatsby-site/i18n/locales/fr/landing.json
  site/gatsby-site/src/components/landing/Hero.js
Labels: PR:Needs Review

#1163 Feature/login btns 2.0
  site/gatsby-site/cypress/e2e/landingPage.cy.js
  site/gatsby-site/cypress/e2e/login.cy.js
  site/gatsby-site/cypress/e2e/signup.cy.js
  site/gatsby-site/cypress/support/commands.js
  site/gatsby-site/i18n/locales/es/login.json
  site/gatsby-site/i18n/locales/fr/login.json
  site/gatsby-site/src/components/loginSignup/index.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/components/ui/Header.js
  site/gatsby-site/src/pages/login.js
  site/gatsby-site/src/pages/signup.js
Labels: PR:Needs Review

#1215 Fix alignment on IncidentStatsCard
  site/gatsby-site/src/components/cite/IncidentStatsCard.js
Labels: PR:Needs Review

#1217 Enable typing in RangeInput
  site/gatsby-site/src/components/discover/filterTypes/RangeInput.js
Labels: PR:Needs Review

#1225 clickable header
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
Labels: PR:Needs Review

#1207 Move SendGrid templates to `sendEmail` function
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/utils/email.js
  site/realm/data_sources/mongodb-atlas/config.json
  site/realm/functions/config.json
  site/realm/functions/confirmUser.js
  site/realm/functions/onIncidentUpdate.js
  site/realm/functions/passwordReset.js
  site/realm/functions/sendEmail.js
  site/realm/triggers/onIncidentUpdate.json
Labels: PR:Needs Review

#1222 Remove description truncation to 200 chars, fix validation
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
Labels: PR:Needs Review

#1208 Feature/notify incident update
  site/realm/functions/onIncidentUpdate.js
  site/realm/functions/sendEmail.js
  site/realm/triggers/onIncidentUpdate.json
Labels: PR:Needs Review

#1226 Add style position inside for li
  site/gatsby-site/src/global.css
Labels: PR:Needs Review

#1067 Switch taxonomy carousel to tailwind, remove hack
  site/gatsby-site/content/taxonomies/index.es.mdx
  site/gatsby-site/content/taxonomies/index.fr.mdx
  site/gatsby-site/content/taxonomies/index.mdx
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/TaxonomyGraphCarousel.js
  site/gatsby-site/src/pages/taxonomies.js
  site/gatsby-site/src/templates/taxonomy.js
  site/gatsby-site/tailwind.config.js
Labels: PR:Needs Review

#1231 fix language switcher test
  site/gatsby-site/cypress/e2e/languageSwitcher.cy.js
Labels: PR:Needs Review

#1024 NLP Incident Detection
  site/gatsby-site/migrations/2022.09.09T14.20.04.add-candidates-collection.js
  site/gatsby-site/src/pages/apps/newsSearch.js
  site/realm/data_sources/mongodb-atlas/aiidprod/candidates/relationships.json
  site/realm/data_sources/mongodb-atlas/aiidprod/candidates/rules.json
  site/realm/data_sources/mongodb-atlas/aiidprod/candidates/schema.json
Labels: PR:Needs Review, Agile:Epic

#1250 Fix blog post opengraph image
  site/gatsby-site/cypress/e2e/blog.cy.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Needs Review

#1257 Fix outdated DB schemas
  site/realm/data_sources/mongodb-atlas/aiidprod/classifications/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
  site/realm/data_sources/mongodb-atlas/customData/subscriptions/schema.json
  site/realm/data_sources/mongodb-atlas/customData/users/schema.json
Labels: PR:Needs Review, Stack:Back End

#1245 Fix sidebar active item on Spanish/French
  site/gatsby-site/cypress/e2e/navigation.cy.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/components/sidebar/tree.js
Labels: Type:Bug, PR:Needs Review, Stack:Front End

#1242 localize paths on `Subscribe` and `Your Account` buttons
  site/gatsby-site/src/components/loginSignup/index.js
Labels: Type:Bug, PR:Mergeable, Stack:Front End

#1206 Query tsne statically, add legend
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/page-creators/createTsneVisualizationPage.js
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/templates/tsneVisualizationPage.js
Labels: PR:Needs Review

#1267 Fix map points on CSET taxonomy page
  site/gatsby-site/src/components/visualizations/LocationMap.js
Labels: Type:Bug, PR:Needs Review

#1260 Fix wrapping on cite tools
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1227 Remove bootstrap styling from apps/incidents layout, blur modal bg
  site/gatsby-site/src/bootstrap.scss
  site/gatsby-site/src/components/discover/QuickAccess.js
  site/gatsby-site/src/pages/apps/incidents.js
Labels: PR:Mergeable

#1271 Remove ref_number field
  site/gatsby-site/cypress/e2e/algolia.cy.js
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/cypress/e2e/downloadIndex.cy.js
  site/gatsby-site/cypress/e2e/translations.cy.js
  site/gatsby-site/migrations/2022.10.14T22.42.50.remove-ref-number.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/QuickAddForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/graphql/submissions.js
  site/gatsby-site/src/pages/summaries/flagged.js
  site/gatsby-site/src/pages/summaries/incidentsOverTime.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
  site/gatsby-site/src/utils/algoliaSettings.js
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
  site/realm/functions/promoteSubmissionToReport.js
Labels: PR:Mergeable

#1279 Add email icon on `Notify me on updates` button
  site/gatsby-site/src/templates/cite.js
Labels: PR:Mergeable

#1291 ListGroup margins
  site/gatsby-site/src/components/WordList.js
  site/gatsby-site/src/components/leaderboards/Leaderboard.js
  site/gatsby-site/src/components/styles/Docs.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/templates/backups.js
  site/gatsby-site/src/templates/wordcounts.js
Labels: PR:Needs Review

#1292 Fix Report edit form
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/cypress/e2e/citeEdit.cy.js
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/i18n/locales/es/submit.json
  site/gatsby-site/i18n/locales/es/validation.json
  site/gatsby-site/i18n/locales/fr/submit.json
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/incidents/IncidentIdField.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/pages/cite/edit.js
Labels: PR:Needs Review

#1288 Prevent 0 from being counted as missing range value
  site/gatsby-site/src/components/discover/filterTypes/RangeInput.js
Labels: PR:Needs Review

#1246 Add newsSearch tests
  site/gatsby-site/cypress/e2e/apps/newsSearch.cy.js
  site/gatsby-site/src/pages/apps/newsSearch.js
Labels: PR:Needs Review

#1297 Use <a> instead of <Link> in September blog post
  site/gatsby-site/blog/incident-report-2022-september/index.es.mdx
  site/gatsby-site/blog/incident-report-2022-september/index.fr.mdx
  site/gatsby-site/blog/incident-report-2022-september/index.mdx
Labels: PR:Needs Review

#1281 Add the ability to enable/disable email notifications
  README.md
  site/realm/functions/sendEmail.js
Labels: PR:Needs Review

#1308 Fix Submission form `description` field validation
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/cypress/fixtures/submissions/submitted.json
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
Labels: PR:Needs Review

#1298 Fix/quick action hover
  site/gatsby-site/src/components/discover/QuickAccess.js
  site/gatsby-site/src/components/sidebar/index.js
Labels: PR:Needs Review

#1236 Feature/subscribe to new incidents
  README.md
  site/gatsby-site/cypress/e2e/account.cy.js
  site/gatsby-site/cypress/e2e/subscriptions.cy.js
  site/gatsby-site/cypress/e2e/unsubscribe.cy.js
  site/gatsby-site/cypress/fixtures/subscriptions/empty-subscriptions.json
  site/gatsby-site/cypress/fixtures/subscriptions/subscriptions.json
  site/gatsby-site/i18n/locales/es/account.json
  site/gatsby-site/i18n/locales/fr/account.json
  site/gatsby-site/src/components/UserSubscriptions.js
  site/gatsby-site/src/pages/unsubscribe.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/utils/subscriptions.js
Labels: PR:Needs Review, Stack:Front End, Stack:Back End

#1237 Feature/send new incident notification
  site/gatsby-site/cypress/e2e/unsubscribe.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/realm/functions/config.json
  site/realm/functions/onNewIncident.js
  site/realm/functions/sendEmail.js
  site/realm/triggers/onNewIncident.json
Labels: PR:Needs Review, Stack:Back End

#1325 Disable subscriptions and notifications to new Incidents
  site/gatsby-site/cypress/e2e/subscriptions.cy.js
  site/gatsby-site/src/components/UserSubscriptions.js
  site/realm/triggers/onNewIncident.json
Labels: PR:Needs Review, Stack:Front End, Stack:Back End
