Repository responsible-ai-collaborative/aiid, pull requests merged in 2022-11, with the labels that each got.

#1332 Add icons to cite tools
  site/gatsby-site/src/components/BibTex.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1080 Feature/submit flowbite
  README.md
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/i18n/locales/en/popovers.json
  site/gatsby-site/i18n/locales/es/popovers.json
  site/gatsby-site/i18n/locales/es/submit.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/popovers.json
  site/gatsby-site/i18n/locales/fr/submit.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/SemanticallyRelatedIncidents.js
  site/gatsby-site/src/components/forms/FlowbiteSearchInput.js
  site/gatsby-site/src/components/forms/Label.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepContainer.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepFour.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepThree.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepTwo.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/forms/Tags.js
  site/gatsby-site/src/components/forms/TagsControl.js
  site/gatsby-site/src/components/forms/TagsInputGroup.js
  site/gatsby-site/src/components/forms/TextInputGroup.js
  site/gatsby-site/src/components/forms/Typeahead.js
  site/gatsby-site/src/components/incidents/IncidentIdField.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionWizard.js
  site/gatsby-site/src/elements/Wizard/index.js
  site/gatsby-site/src/pages/apps/submit.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1331 Change pending notification process
  README.md
  site/gatsby-site/cypress/e2e/functions/onNewIncident.cy.js
  site/gatsby-site/cypress/e2e/functions/processNotifications.cy.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/postBuild/processNotifications.js
  site/realm/data_sources/mongodb-atlas/customData/notifications/relationships.json
  site/realm/data_sources/mongodb-atlas/customData/notifications/rules.json
  site/realm/data_sources/mongodb-atlas/customData/notifications/schema.json
  site/realm/functions/config.json
  site/realm/functions/onNewIncident.js
  site/realm/functions/processNotifications.js
  site/realm/functions/sendEmail.js
  site/realm/graphql/custom_resolvers/mutation_processNotifications.json
  site/realm/triggers/onNewIncident.json
Labels: PR:Needs Review, Stack:Back End

#1312 Create entities collection
  site/gatsby-site/cypress/e2e/apps/incidents.cy.js
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/fixtures/incidents/incident.json
  site/gatsby-site/cypress/fixtures/incidents/incident112.json
  site/gatsby-site/cypress/fixtures/incidents/incidentWithDeletedReport.json
  site/gatsby-site/cypress/fixtures/incidents/incidents.json
  site/gatsby-site/cypress/fixtures/incidents/updateOneIncident112.json
  site/gatsby-site/cypress/fixtures/incidents/updateOneIncidentFlagged.json
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/migrations/2022.10.24T21.52.43.create-entities-collection.js
  site/gatsby-site/page-creators/createEntitiesPages.js
  site/gatsby-site/src/components/entities/CommonEntities.js
  site/gatsby-site/src/components/forms/Label.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/forms/Typeahead.js
  site/gatsby-site/src/components/incidents/IncidentEditModal.js
  site/gatsby-site/src/components/incidents/IncidentsTable.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/graphql/entities.js
  site/gatsby-site/src/graphql/incidents.js
  site/gatsby-site/src/graphql/submissions.js
  site/gatsby-site/src/pages/incidents/edit.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/utils/entities.js
  site/realm/data_sources/mongodb-atlas/aiidprod/entities/relationships.json
  site/realm/data_sources/mongodb-atlas/aiidprod/entities/rules.json
  site/realm/data_sources/mongodb-atlas/aiidprod/entities/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/incidents/relationships.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/relationships.json
Labels: PR:Needs Review, Stack:Back End

#1352 Re-enable subscription to New Incidents option
  site/gatsby-site/cypress/e2e/subscriptions.cy.js
  site/gatsby-site/src/components/UserSubscriptions.js
Labels: PR:Needs Review, Stack:Front End

#1356 Pre-Deploy
  site/realm/triggers/onIncidentUpdate.json
  site/realm/triggers/onNewIncident.json
Labels: Stack:Back End

#1368 Fix/Form error handling
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepTwo.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/submissions/SubmissionWizard.js
Labels: PR:Needs Review

#1364 Fix form error on entities
  site/gatsby-site/src/utils/entities.js
Labels: PR:Needs Review

#1350 Subscribe to Entity new incidents
  README.md
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/e2e/entity.cy.js
  site/gatsby-site/cypress/e2e/subscriptions.cy.js
  site/gatsby-site/cypress/fixtures/subscriptions/subscriptions.json
  site/gatsby-site/i18n/locales/es/account.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/account.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/UserSubscriptions.js
  site/gatsby-site/src/graphql/subscriptions.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/utils/entities.js
  site/gatsby-site/src/utils/subscriptions.js
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/relationships.json
  site/realm/data_sources/mongodb-atlas/customData/subscriptions/relationships.json
  site/realm/data_sources/mongodb-atlas/customData/subscriptions/schema.json
Labels: PR:Needs Review, Stack:Front End, Stack:Back End

#1388 Translate october blog post to french
  site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
Labels: PR:Needs Review

#1369 Submit Form / don't show errors when clicking fetch info
  site/gatsby-site/src/components/forms/FlowbiteSearchInput.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/submissions/SubmissionWizard.js
  site/gatsby-site/src/elements/Wizard/index.js
Labels: PR:Needs Review

#1393 Only process notifications if CONTEXT=production
  site/gatsby-site/cypress/e2e/functions/processNotifications.cy.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/postBuild/processNotifications.js
  site/realm/functions/processNotifications.js
  site/realm/graphql/custom_resolvers/mutation_processNotifications.json
Labels: PR:Needs Review, Stack:Back End

#1328 Update list style to avoid hardcoded revert style
  site/gatsby-site/blog/incident-report-2022-october/index.es.mdx
  site/gatsby-site/blog/incident-report-2022-october/index.fr.mdx
  site/gatsby-site/blog/incident-report-2022-october/index.mdx
  site/gatsby-site/blog/incident-report-2022-september/index.es.mdx
  site/gatsby-site/blog/incident-report-2022-september/index.fr.mdx
  site/gatsby-site/blog/incident-report-2022-september/index.mdx
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/components/entities/CommonEntities.js
  site/gatsby-site/src/components/layout/Footer.js
  site/gatsby-site/src/components/reports/ReportText.js
  site/gatsby-site/src/components/rightSidebar.js
  site/gatsby-site/src/components/sidebar/treeNode.js
  site/gatsby-site/src/components/visualizations/Timeline.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/pages/taxonomies.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/backups.js
  site/gatsby-site/src/templates/docs.js
  site/gatsby-site/src/templates/post.js
  site/gatsby-site/src/templates/taxonomy.js
  site/gatsby-site/src/templates/wordcounts.js
  site/gatsby-site/tailwind.config.js
Labels: PR:Needs Review

#1355 Fix canonical urls
  site/gatsby-site/config.js
  site/gatsby-site/content/research/4-related-work/index.es.mdx
  site/gatsby-site/content/research/4-related-work/index.fr.mdx
  site/gatsby-site/content/research/4-related-work/index.mdx
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/src/components/AiidHelmet.js
  site/gatsby-site/src/pages/account.js
  site/gatsby-site/src/pages/apps/classifications.js
  site/gatsby-site/src/pages/apps/discover.js
  site/gatsby-site/src/pages/apps/incidents.js
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/pages/apps/submit.js
  site/gatsby-site/src/pages/apps/submitted.js
  site/gatsby-site/src/pages/blog/index.js
  site/gatsby-site/src/pages/summaries/flagged.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/pages/summaries/leaderboard.js
  site/gatsby-site/src/pages/taxonomies.js
  site/gatsby-site/src/templates/backups.js
  site/gatsby-site/src/templates/docs.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/templates/taxonomy.js
  site/gatsby-site/src/templates/wordcounts.js
Labels: PR:Needs Review

#1412 Add check for existence of canonicalUrl before indexing into it
  site/gatsby-site/src/components/AiidHelmet.js
  site/gatsby-site/src/templates/cite-duplicate.js
Labels: PR:Needs Review

#1415 Fix issues Issues
  site/gatsby-site/cypress/e2e/functions/promoteSubmissionToReport.cy.js
  site/gatsby-site/src/components/discover/Actions.js
  site/realm/functions/promoteSubmissionToReport.js
Labels: PR:Mergeable

#1402 Entity responses count
  site/gatsby-site/cypress/e2e/entities.cy.js
  site/gatsby-site/cypress/e2e/landingPage.cy.js
  site/gatsby-site/cypress/e2e/pageCreators/createEntitiesPages.cy.js
  site/gatsby-site/i18n/locales/es/entities.json
  site/gatsby-site/i18n/locales/fr/entities.json
  site/gatsby-site/page-creators/createEntitiesPages.js
  site/gatsby-site/src/components/entities/CommonEntities.js
  site/gatsby-site/src/components/entities/EntitiesTable.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/utils/entities.js
Labels: PR:Needs Review, Stack:Front End, Stack:Back End

#1405 Feature/response annotations
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/visualizations/Timeline.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1400 Feature/response button
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/i18n/locales/es/submit.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/submit.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/pages/apps/submit.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1417 Incident Responses
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/e2e/entities.cy.js
  site/gatsby-site/cypress/e2e/landingPage.cy.js
  site/gatsby-site/cypress/e2e/pageCreators/createEntitiesPages.cy.js
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/i18n/locales/es/entities.json
  site/gatsby-site/i18n/locales/es/submit.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/entities.json
  site/gatsby-site/i18n/locales/fr/submit.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/page-creators/createEntitiesPages.js
  site/gatsby-site/src/components/entities/CommonEntities.js
  site/gatsby-site/src/components/entities/EntitiesTable.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/components/visualizations/Timeline.js
  site/gatsby-site/src/pages/apps/submit.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/utils/entities.js
Labels: Stack:Front End, Stack:Back End

#1385 Defining an incident response
  site/gatsby-site/config.js
  site/gatsby-site/content/research/5-response/index.es.mdx
  site/gatsby-site/content/research/5-response/index.fr.mdx
  site/gatsby-site/content/research/5-response/index.mdx
  site/gatsby-site/src/components/ui/MdxComponents.js
Labels: PR:Needs Review

#1351 Add configurable right sidebar
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/Outline.js
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/components/taxa/Taxonomy.js
  site/gatsby-site/src/elements/Pagination/index.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/docs.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Needs Review
