Repository responsible-ai-collaborative/aiid, pull requests merged in 2022-09, with the labels that each got.

#1048 Make 1st report only switch persist refresh
  site/gatsby-site/src/components/discover/Controls.js
  site/gatsby-site/src/components/discover/Hits.js
  site/gatsby-site/src/components/discover/OptionsModal.js
  site/gatsby-site/src/components/discover/queryParams.js
  site/gatsby-site/src/pages/apps/discover.js
Labels: PR:Needs Review

#1055 Disable flowbite Dark mode
  site/gatsby-site/tailwind.config.js
Labels: PR:Needs Review

#1046 Fix/link color and missing italic texts
  site/gatsby-site/src/components/landing/AboutDatabase .js
  site/gatsby-site/src/components/landing/Sponsors.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1042 Add light-outline variant to language switcher
  site/gatsby-site/src/components/i18n/LanguageSwitcher.js
Labels: PR:Needs Review

#1044 Fix TSNE page wording issues
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/templates/tsneVisualizationPage.js
Labels: PR:Needs Review

#979 Restructuring
  site/gatsby-site/config.js
  site/gatsby-site/content/taxonomies/index.es.mdx
  site/gatsby-site/content/taxonomies/index.mdx
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/src/components/TaxonomyGraphCarousel.js
  site/gatsby-site/src/components/layout/Footer.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/components/sidebar/treeNode.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/taxonomy.js
Labels: PR:Needs Review

#1054 Hide Google authentication
  README.md
  site/gatsby-site/src/contexts/userContext/UserContext.js
  site/gatsby-site/src/contexts/userContext/UserContextProvider.js
  site/gatsby-site/src/pages/login.js
  site/gatsby-site/src/pages/signup.js
  site/realm/auth/providers.json
  site/realm/triggers/onNewUser.json
Labels: PR:Needs Review

#1070 Fix tsne visualization and popovers
  site/gatsby-site/src/bootstrap.scss
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/components/forms/Label.js
Labels: PR:Needs Review

#1076 Fix promote submission to report
  site/gatsby-site/migrations/2022.09.09T20.08.13.create-reports-and-incidents-index.js
Labels: PR:Needs Review

#1078 Add margin to footer headings
  site/gatsby-site/src/components/layout/Footer.js
Labels: PR:Needs Review

#1082 Fix positioning of translation badge
  site/gatsby-site/cypress/e2e/translationBadge.cy.js
  site/gatsby-site/src/components/i18n/TranslationBadge.js
  site/gatsby-site/src/components/ui/WebArchiveLink.js
  site/gatsby-site/src/templates/docs.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Work Needed

#1086 Fix taxonomy page styles
  site/gatsby-site/cypress/e2e/taxonomy/cset.cy.js
  site/gatsby-site/src/templates/taxonomy.js
Labels: PR:Needs Review

#1085 Fix flag report Button
  site/gatsby-site/src/components/discover/Actions.js
Labels: PR:Needs Review

#1091 Fix Tools btns margin right
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1026 Restore text outline in right sidebar
  site/gatsby-site/cypress/e2e/blog.cy.js
  site/gatsby-site/src/components/rightSidebar.js
Labels: PR:Mergeable

#1079 Add helmet to /apps/incidents
  site/gatsby-site/src/pages/apps/incidents.js
Labels: PR:Needs Review

#1039 Improve blog cards styling
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/theme/index.js
  site/gatsby-site/src/pages/blog/index.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Mergeable

#1019 Switch to table on /summaries/flagged
  site/gatsby-site/src/pages/summaries/flagged.js
Labels: PR:Mergeable

#1057 Add engineering processes to readme
  README.md
Labels: PR:Needs Review

#1105 Fix submitted margins
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/pages/apps/submitted.js
Labels: PR:Needs Review

#988 Simplify submission form
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/i18n/locales/en/popovers.json
  site/gatsby-site/i18n/locales/es/popovers.json
  site/gatsby-site/i18n/locales/es/submit.json
  site/gatsby-site/i18n/locales/es/validation.json
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/forms/Tags.js
  site/gatsby-site/src/components/forms/TagsControl.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Mergeable

#1062 Apply Flowbite Button with Spinner
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/cypress/fixtures/submissions/quickadds.json
  site/gatsby-site/i18n/locales/es/submit.json
  site/gatsby-site/i18n/locales/es/submitted.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/components/discover/Actions.js
  site/gatsby-site/src/components/discover/Hits.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/incidents/IncidentEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionList.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/pages/apps/classifications.js
  site/gatsby-site/src/pages/apps/incidents.js
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/pages/apps/submitted.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/pages/incidents/edit.js
  site/gatsby-site/src/pages/login.js
  site/gatsby-site/src/pages/logout.js
  site/gatsby-site/src/pages/signup.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1087 Add email verification on Email signup
  README.md
  site/gatsby-site/cypress/e2e/signup.cy.js
  site/gatsby-site/i18n/locales/es/login.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/contexts/userContext/UserContext.js
  site/gatsby-site/src/contexts/userContext/UserContextProvider.js
  site/gatsby-site/src/pages/confirmemail.js
  site/gatsby-site/src/pages/signup.js
  site/realm/auth/providers.json
  site/realm/functions/confirmUser.js
  site/realm/values/SendGridApiKey.json
Labels: PR:Needs Review

#1093 Custom Password reset email
  site/gatsby-site/src/contexts/userContext/UserContextProvider.js
  site/realm/auth/providers.json
  site/realm/functions/config.json
  site/realm/functions/passwordReset.js
Labels: PR:Needs Review

#1000 Tailwind/ navigation (sidebar)
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: PR:Work Needed

#1090 Fix popovers across site
  site/gatsby-site/src/components/forms/Label.js
  site/gatsby-site/src/components/taxa/Taxonomy.js
  site/gatsby-site/src/components/visualizations/Timeline.js
  site/gatsby-site/src/elements/PopoverWrapper/index.js
Labels: PR:Needs Review

#1071 Quick access buttons, headings, and alignment
  site/gatsby-site/content/about/index.es.mdx
  site/gatsby-site/content/about/index.mdx
  site/gatsby-site/content/privacy-policy/index.es.mdx
  site/gatsby-site/content/privacy-policy/index.mdx
  site/gatsby-site/content/research/1-criteria/index.es.mdx
  site/gatsby-site/content/research/1-criteria/index.mdx
  site/gatsby-site/content/research/2-roadmap/index.es.mdx
  site/gatsby-site/content/research/2-roadmap/index.mdx
  site/gatsby-site/content/research/index.es.mdx
  site/gatsby-site/content/research/index.mdx
  site/gatsby-site/content/terms-of-use/index.es.mdx
  site/gatsby-site/content/terms-of-use/index.mdx
  site/gatsby-site/src/components/discover/QuickAccess.js
  site/gatsby-site/src/components/rightSidebar.js
  site/gatsby-site/src/components/styles/Docs.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1047 Improve landing styles
  site/gatsby-site/cypress/e2e/submitter.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/WordList.js
  site/gatsby-site/src/components/blog/LatestPost.js
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/forms/QuickAddForm.js
  site/gatsby-site/src/components/landing/AboutDatabase .js
  site/gatsby-site/src/components/landing/Blog.js
  site/gatsby-site/src/components/landing/Featured.js
  site/gatsby-site/src/components/landing/Hero.js
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
  site/gatsby-site/src/components/landing/LatestReports.js
  site/gatsby-site/src/components/landing/Leaderboards.js
  site/gatsby-site/src/components/landing/QuickAdd.js
  site/gatsby-site/src/components/landing/QuickSearch.js
  site/gatsby-site/src/components/landing/RandomIncidentsCarousel.js
  site/gatsby-site/src/components/landing/RandomReports.js
  site/gatsby-site/src/components/landing/Sponsors.js
  site/gatsby-site/src/components/landing/WordCounts.js
  site/gatsby-site/src/components/leaderboards/Leaderboard.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/landingPage.js
  site/gatsby-site/src/utils/cloudinary.js
  site/gatsby-site/tailwind.config.js
Labels: PR:Needs Review

#1099 Feature/flowbite readme
  README.md
Labels: PR:Needs Review

#1151 Add Latest Incident Report inside card
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
  site/gatsby-site/src/components/landing/LatestReports.js
Labels: PR:Needs Review

#1002 Email notifications subscription to Incident updates
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/e2e/languageSwitcher.cy.js
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
  site/gatsby-site/src/components/landing/LatestReports.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/contexts/userContext/UserContext.js
  site/gatsby-site/src/graphql/submissions.js
  site/gatsby-site/src/graphql/subscriptions.js
  site/gatsby-site/src/graphql/users.js
  site/gatsby-site/src/templates/cite.js
  site/realm/data_sources/mongodb-atlas/aiidprod/incidents/schema.json
  site/realm/data_sources/mongodb-atlas/customData/subscriptions/relationships.json
  site/realm/data_sources/mongodb-atlas/customData/subscriptions/rules.json
  site/realm/data_sources/mongodb-atlas/customData/subscriptions/schema.json
  site/realm/data_sources/mongodb-atlas/customData/users/relationships.json
  site/realm/data_sources/mongodb-atlas/customData/users/rules.json
  site/realm/data_sources/mongodb-atlas/customData/users/schema.json
  site/realm/functions/config.json
  site/realm/functions/getUser.js
  site/realm/functions/sendEmail.js
  site/realm/graphql/custom_resolvers/mutation_getUser.json
  site/realm/values/appId.json
  site/realm/values/groupId.json
  site/realm/values/privateApiKey.json
  site/realm/values/publicApiKey.json
Labels: PR:Needs Review

#1168 Change `1600` report count to `1800`
  site/gatsby-site/i18n/locales/es/landing.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/landing.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/landing/QuickSearch.js
Labels: PR:Mergeable

#1138 Footer Structure and Orphaned Page Breakup
  site/gatsby-site/config.js
  site/gatsby-site/content/research/1-criteria/index.es.mdx
  site/gatsby-site/content/research/1-criteria/index.fr.mdx
  site/gatsby-site/content/research/1-criteria/index.mdx
  site/gatsby-site/content/research/4-related-work/index.es.mdx
  site/gatsby-site/content/research/4-related-work/index.fr.mdx
  site/gatsby-site/content/research/4-related-work/index.mdx
  site/gatsby-site/content/research/index.es.mdx
  site/gatsby-site/content/research/index.fr.mdx
  site/gatsby-site/content/research/index.mdx
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/src/templates/backups.js
Labels: PR:Needs Review

#1181 Login infinite loading
  site/gatsby-site/src/contexts/userContext/UserContextProvider.js
Labels: PR:Needs Review

#1158 Update landing page carousel style
  site/gatsby-site/src/components/landing/RandomIncidentsCarousel.js
  site/gatsby-site/src/components/landing/RandomReports.js
  site/gatsby-site/src/templates/landingPage.js
Labels: PR:Needs Review
