Repository responsible-ai-collaborative/aiid, pull requests merged in 2022-06, with the labels that each got.

#640 Auto-update image preview, add label, and set max size
  site/gatsby-site/cypress/integration/apps/incidents.js
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/src/components/cite/Citation.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/incidents/IncidentForm.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#670 Stop extra requests on typing image urls, show errors
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#673 Fix submission form
  site/gatsby-site/cypress/integration/apps/submitted.js
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/migrations/2022.06.02T20.54.45.source-domain-update.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/incidents/IncidentIdField.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/graphql/submissions.js
Labels: PR:Needs Review

#671 Add a11y skip-to-content link
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/LayoutHideSidebar.js
  site/gatsby-site/src/components/ui/Header.js
Labels: PR:Needs Review

#526 Support markdown formatting on reports' text property
  site/gatsby-site/cypress/fixtures/api/parseNews.json
  site/gatsby-site/cypress/fixtures/classifications/allClassifications.json
  site/gatsby-site/cypress/fixtures/reports/flagged.json
  site/gatsby-site/cypress/fixtures/reports/report.json
  site/gatsby-site/cypress/fixtures/reports/unflagged.json
  site/gatsby-site/cypress/fixtures/submissions/submitted.json
  site/gatsby-site/cypress/integration/apps/submitted.js
  site/gatsby-site/cypress/integration/cite.js
  site/gatsby-site/cypress/integration/citeEdit.js
  site/gatsby-site/cypress/integration/discoverIndexGenerator.js
  site/gatsby-site/cypress/integration/downloadIndex.js
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/cypress/integration/translations.js
  site/gatsby-site/cypress/support/commands.js
  site/gatsby-site/cypress/support/index.d.ts
  site/gatsby-site/cypress/support/index.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/migrations/2022.05.30T21.37.38.markdown-format.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/api/parseNews.js
  site/gatsby-site/src/components/cite/IncidentCard.js
  site/gatsby-site/src/components/discover/Hits.js
  site/gatsby-site/src/components/discover/hitTypes/Details.js
  site/gatsby-site/src/components/discover/hitTypes/List.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/reports/ReportText.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/components/taxa/Taxonomy.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/graphql/reports.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
  site/gatsby-site/src/utils/Translator.js
  site/gatsby-site/src/utils/discoverIndexGenerator.js
  site/gatsby-site/src/utils/typography.js
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
Labels: PR:Needs Review

#688 Strip www, m from source_domains
  site/gatsby-site/cypress/integration/citeEdit.js
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/migrations/2022.06.07T17.24.11.normalize-domains.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/QuickAddForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/utils/getSourceDomain.js
Labels: PR:Needs Review

#677 Editor notes
  site/gatsby-site/cypress/fixtures/reports/flagged.json
  site/gatsby-site/cypress/fixtures/reports/report.json
  site/gatsby-site/cypress/fixtures/reports/unflagged.json
  site/gatsby-site/cypress/fixtures/reports/updateOneReport.json
  site/gatsby-site/cypress/fixtures/submissions/submitted.json
  site/gatsby-site/cypress/integration/citeEdit.js
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/migrations/2022.06.03T17.58.30.add-blank-editor-notes-fields.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/graphql/reports.js
  site/gatsby-site/src/graphql/submissions.js
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
Labels: PR:Work Needed

#726 Add editor_notes to submit tests and check submitted data
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
Labels: PR:Mergeable

#741 reworked sponsor block
  site/gatsby-site/content/about.mdx
  site/gatsby-site/cypress/integration/landingPage.js
  site/gatsby-site/src/components/landing/AboutPartnership.js
  site/gatsby-site/src/components/landing/Founding.js
  site/gatsby-site/src/components/landing/Sponsors.js
  site/gatsby-site/src/components/landing/assets/cloudinary_cloud_glyph_regular.svg
  site/gatsby-site/src/components/landing/assets/netlify-dark.svg
  site/gatsby-site/src/components/landing/assets/partership-on-ai-logo.png
  site/gatsby-site/src/components/landing/assets/wu-foundation-blue-logo.svg
  site/gatsby-site/src/templates/landingPage.js
Labels: PR:Mergeable

#736 Add semantically similar reports to submission page
  site/gatsby-site/cypress/integration/submit.js
  site/gatsby-site/src/api/semanticallyRelated.js
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/SemanticallyRelatedIncidents.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
Labels: PR:Needs Review
