Repository responsible-ai-collaborative/aiid, pull requests merged in 2022-07, with the labels that each got.

#762 Remove Gitter from README.md
  README.md
Labels: PR:Mergeable

#751 Upgrade to latest version of cypress
  site/gatsby-site/cypress.config.js
  site/gatsby-site/cypress.json
  site/gatsby-site/cypress/e2e/apps/classifications.cy.js
  site/gatsby-site/cypress/e2e/apps/incidents.cy.js
  site/gatsby-site/cypress/e2e/apps/reports.cy.js
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/e2e/citeEdit.cy.js
  site/gatsby-site/cypress/e2e/discover.cy.js
  site/gatsby-site/cypress/e2e/downloadIndex.cy.js
  site/gatsby-site/cypress/e2e/incidents.cy.js
  site/gatsby-site/cypress/e2e/integrity.cy.js
  site/gatsby-site/cypress/e2e/landingPage.cy.js
  site/gatsby-site/cypress/e2e/navigation.cy.js
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/cypress/e2e/summaries/flagged.cy.js
  site/gatsby-site/cypress/e2e/summaries/incidents.cy.js
  site/gatsby-site/cypress/e2e/taxonomy/cset.cy.js
  site/gatsby-site/cypress/e2e/translations.cy.js
  site/gatsby-site/cypress/e2e/wordcounts.cy.js
  site/gatsby-site/cypress/support/e2e.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
Labels: PR:Mergeable

#763 Fix empty plain text on some reports
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/migrations/2022.07.04T18.32.55.plain_text-fix.js
  site/gatsby-site/src/graphql/submissions.js
Labels: PR:Mergeable

#765 Translate citation pages
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/i18n/locales/en/actions.json
  site/gatsby-site/i18n/locales/es/actions.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/BibTex.js
  site/gatsby-site/src/components/cite/IncidentCard.js
  site/gatsby-site/src/components/cite/IncidentStatsCard.js
  site/gatsby-site/src/components/discover/Actions.js
  site/gatsby-site/src/components/taxa/Taxonomy.js
  site/gatsby-site/src/hooks/useModal.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Mergeable

#793 Add Login e2e test
  site/gatsby-site/cypress/e2e/login.cy.js
Labels: PR:Needs Review

#780 i18n for content pages
  site/gatsby-site/blog/join-raic/index.es.mdx
  site/gatsby-site/blog/join-raic/index.mdx
  site/gatsby-site/blog/representation-and-imagination/index.es.mdx
  site/gatsby-site/blog/representation-and-imagination/index.mdx
  site/gatsby-site/blog/the-first-taxonomy-of-ai-incidents/index.es.mdx
  site/gatsby-site/blog/the-first-taxonomy-of-ai-incidents/index.mdx
  site/gatsby-site/content/about/index.es.mdx
  site/gatsby-site/content/about/index.mdx
  site/gatsby-site/content/about_apps/index.es.mdx
  site/gatsby-site/content/about_apps/index.mdx
  site/gatsby-site/content/contact/index.es.mdx
  site/gatsby-site/content/contact/index.mdx
  site/gatsby-site/content/research/1-criteria/index.es.mdx
  site/gatsby-site/content/research/1-criteria/index.mdx
  site/gatsby-site/content/research/2-roadmap/index.es.mdx
  site/gatsby-site/content/research/2-roadmap/index.mdx
  site/gatsby-site/content/research/3-history/index.es.mdx
  site/gatsby-site/content/research/3-history/index.mdx
  site/gatsby-site/content/research/index.es.mdx
  site/gatsby-site/content/research/index.mdx
  site/gatsby-site/content/taxonomies/index.es.mdx
  site/gatsby-site/content/taxonomies/index.mdx
  site/gatsby-site/gatsby-browser.js
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/gatsby-ssr.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/page-creators/createMdxPages.js
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/LayoutHideSidebar.js
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/discover/QuickAccess.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/components/sidebar/treeNode.js
  site/gatsby-site/src/components/ui/Link.js
  site/gatsby-site/src/pages/blog/{mdx.slug}.js
  site/gatsby-site/src/templates/docs.js
  site/gatsby-site/src/templates/downloadIndex.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Needs Review

#817 Fix memory leak in quicksearch
  site/gatsby-site/src/components/landing/QuickSearch.js
Labels: PR:Needs Review

#789 Add submitter e2e test
  site/gatsby-site/cypress/e2e/submitter.cy.js
Labels: PR:Needs Review

#829 Add all-hands blog post
  site/gatsby-site/blog/raic-holds-first-all-hands-meeting/index.es.mdx
  site/gatsby-site/blog/raic-holds-first-all-hands-meeting/index.mdx
  site/gatsby-site/src/images/raic-global-team.png
Labels: PR:Needs Review

#802 Improve OpenGraph meta tags #697
  site/gatsby-site/config.js
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/src/html.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#820 Make `WebArchiveLink`s split buttons with original and archive urls
  site/gatsby-site/cypress/e2e/discover.cy.js
  site/gatsby-site/src/components/cite/IncidentCard.js
  site/gatsby-site/src/components/discover/hitTypes/Compact.js
  site/gatsby-site/src/components/discover/hitTypes/shared.js
  site/gatsby-site/src/components/ui/WebArchiveLink.js
Labels: PR:Needs Review

#815 Fix Location taxonomy map chart
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/visualizations/useWorldAtlas.js
  site/gatsby-site/src/templates/taxonomy.js
Labels: Type:Bug, PR:Needs Review, Stack:Front End

#801 README: Add PR labeling strategy and basic development workflow
  README.md
Labels: PR:Mergeable

#777 Discover incident variety
  site/gatsby-site/cypress/e2e/apps/classifications.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/discover/Controls.js
  site/gatsby-site/src/components/discover/DisplayModeSwitch.js
  site/gatsby-site/src/components/discover/OptionsModal.js
  site/gatsby-site/src/pages/apps/discover.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
Labels: PR:Needs Review

#783 Add z-index to main and right sidebar
  site/gatsby-site/src/components/Layout.js
Labels: PR:Needs Review

#861 Create 404 images Migration
  site/gatsby-site/migrations/2022.07.26T17.46.22.fix-404-report-images.js
Labels: PR:Needs Review

#842 Remove custom html.js
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/src/components/AiidHelmet.js
  site/gatsby-site/src/html.js
  site/gatsby-site/src/pages/404.js
  site/gatsby-site/src/pages/apps/classifications.js
  site/gatsby-site/src/pages/apps/discover.js
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/pages/apps/submit.js
  site/gatsby-site/src/pages/apps/submitted.js
  site/gatsby-site/src/pages/summaries/flagged.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/pages/summaries/leaderboard.js
  site/gatsby-site/src/pages/wordcounts.js
  site/gatsby-site/src/templates/backups.js
  site/gatsby-site/src/templates/cite-duplicate.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/docs.js
  site/gatsby-site/src/templates/landingPage.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Needs Review

#761 Similar Incidents
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.es.mdx
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.mdx
  site/gatsby-site/cypress/e2e/apps/incidents.cy.js
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/e2e/submit.cy.js
  site/gatsby-site/cypress/fixtures/incidents/incident.json
  site/gatsby-site/cypress/fixtures/incidents/incident112.json
  site/gatsby-site/cypress/fixtures/incidents/incidents.json
  site/gatsby-site/cypress/fixtures/incidents/updateOneIncident.json
  site/gatsby-site/cypress/fixtures/incidents/updateOneIncident112.json
  site/gatsby-site/cypress/fixtures/reports/flagged.json
  site/gatsby-site/cypress/fixtures/reports/report.json
  site/gatsby-site/cypress/fixtures/reports/unflagged.json
  site/gatsby-site/cypress/fixtures/reports/updateOneReport.json
  site/gatsby-site/cypress/fixtures/submissions/submitted.json
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/migrations/2022.06.23T20.09.47.initialize-empty-nlp-similar-incidents.js
  site/gatsby-site/migrations/2022.06.23T21.14.51.add-similar-incidents.js
  site/gatsby-site/migrations/2022.07.01T01.56.38.initialize-editor-similar-dissimilar-incidents.js
  site/gatsby-site/migrations/2022.07.01T20.26.13.initialize-empty-flagged-dissimilar-incidents.js
  site/gatsby-site/page-creators/createCitationPages.js
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/SemanticallyRelatedIncidents.js
  site/gatsby-site/src/components/SimilaritySelector.js
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/incidents/IncidentForm.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/graphql/incidents.js
  site/gatsby-site/src/graphql/submissions.js
  site/gatsby-site/src/images/nlp-lambdas-aws-architecture.png
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/static/images/ai2.png
  site/gatsby-site/static/images/docker.png
  site/gatsby-site/static/images/nlp-lambdas-aws-architecture.png
  site/gatsby-site/static/semantically-related.mp4
  site/realm/data_sources/mongodb-atlas/aiidprod/incidents/rules.json
  site/realm/data_sources/mongodb-atlas/aiidprod/incidents/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
  site/realm/functions/promoteSubmissionToReport.js
Labels: PR:Mergeable

#874 update NLP blog post
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.es.mdx
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.mdx
Labels: PR:Mergeable

#875 Add `cursor: pointer` to “1st report only” switch
  site/gatsby-site/src/components/discover/Controls.js
Labels: PR:Needs Review

#880 Add project architecture diagram
  README.md
Labels: PR:Needs Review
