Repository responsible-ai-collaborative/aiid, pull requests merged in 2022-08, with the labels that each got.

#848 Render jsx in popovers, click to toggle visibility
  site/gatsby-site/src/components/forms/Label.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/ui/PopOvers.js
  site/gatsby-site/src/components/ui/Popover.js
Labels: PR:Needs Review

#864 Allow editing translations on edit report form
  site/gatsby-site/cypress/e2e/citeEdit.cy.js
  site/gatsby-site/cypress/fixtures/reports/reportWithTranslations.json
  site/gatsby-site/cypress/fixtures/reports/updateOneReportTranslation.json
  site/gatsby-site/cypress/support/commands.js
  site/gatsby-site/cypress/support/index.d.ts
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/graphql/reports.js
  site/gatsby-site/src/pages/cite/edit.js
  site/realm/data_sources/mongodb-atlas/aiidprod/incidents/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
  site/realm/data_sources/mongodb-atlas/translations/reports_en/rules.json
  site/realm/data_sources/mongodb-atlas/translations/reports_es/rules.json
  site/realm/functions/config.json
  site/realm/functions/reportTranslations.js
  site/realm/functions/updateOneReportTranslation.js
  site/realm/graphql/custom_resolvers/mutation_updateOneReportTranslation.json
  site/realm/graphql/custom_resolvers/report_translations.json
Labels: PR:Mergeable

#878 Delete report from incident when report is deleted
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/cypress/e2e/citeEdit.cy.js
  site/gatsby-site/cypress/fixtures/incidents/incidentWithDeletedReport.json
  site/gatsby-site/migrations/2022.07.28T20.09.26.remove-invalid-references.js
  site/gatsby-site/src/components/cite/IncidentCard.js
  site/gatsby-site/src/components/visualizations/Timeline.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#882 Mention algolia-update.js script in readme
  README.md
Labels: PR:Needs Review

#852 Switch quicksearch placeholder text determination from js to css
  site/gatsby-site/src/components/forms/SearchInput.js
  site/gatsby-site/src/components/landing/QuickSearch.js
Labels: PR:Needs Review

#879 Update OpenGraph meta tags to use incident title and description
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/page-creators/createCitationPages.js
  site/gatsby-site/src/components/AiidHelmet.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Mergeable

#857 Use request body instead of query parameters for semanticallyRelated
  site/gatsby-site/src/api/semanticallyRelated.js
  site/gatsby-site/src/components/SemanticallyRelatedIncidents.js
Labels: PR:Needs Review

#897 Feature i18n badge
  site/gatsby-site/blog/join-raic/index.es.mdx
  site/gatsby-site/blog/raic-holds-first-all-hands-meeting/index.es.mdx
  site/gatsby-site/blog/representation-and-imagination/index.es.mdx
  site/gatsby-site/blog/the-first-taxonomy-of-ai-incidents/index.es.mdx
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.es.mdx
  site/gatsby-site/content/about/index.es.mdx
  site/gatsby-site/content/about_apps/index.es.mdx
  site/gatsby-site/content/contact/index.es.mdx
  site/gatsby-site/content/privacy-policy/index.es.mdx
  site/gatsby-site/content/research/1-criteria/index.es.mdx
  site/gatsby-site/content/research/2-roadmap/index.es.mdx
  site/gatsby-site/content/research/3-history/index.es.mdx
  site/gatsby-site/content/research/index.es.mdx
  site/gatsby-site/content/taxonomies/index.es.mdx
  site/gatsby-site/content/terms-of-use/index.es.mdx
  site/gatsby-site/cypress/e2e/translationBadge.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/cite/IncidentCard.js
  site/gatsby-site/src/components/discover/hitTypes/Details.js
  site/gatsby-site/src/components/discover/hitTypes/List.js
  site/gatsby-site/src/components/i18n/TranslationBadge.js
  site/gatsby-site/src/components/styles/Docs.js
  site/gatsby-site/src/components/styles/Post.js
  site/gatsby-site/src/templates/docs.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Mergeable

#792 Make images load fallback on failed request, add extra escape
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#822 Feature/tailwind css - step1 - installation
  site/gatsby-site/gatsby-browser.js
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/postcss.config.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: Type:Enhancement, Stack:Front End

#825 Feature/tailwind blog listing
  site/gatsby-site/cypress/support/commands.js
  site/gatsby-site/gatsby-browser.js
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/blog/PostsListing.js
  site/gatsby-site/src/components/styles/Docs.js
  site/gatsby-site/src/custom.css
  site/gatsby-site/src/elements/Card/index.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: Type:Enhancement, PR:Needs Review, Stack:Front End

#931 Fix language switcher UI issue
  site/gatsby-site/src/components/forms/SearchInput.js
Labels: PR:Mergeable

#885 Social Share Buttons
  site/gatsby-site/cypress/e2e/socialShareButtons.cy.js
  site/gatsby-site/i18n/locales/es/submitted.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/components/ui/SocialShareButtons.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Needs Review

#841 Feature/tailwind cite
  site/gatsby-site/cypress/e2e/cite.cy.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/src/components/cite/ImageCarousel.js
  site/gatsby-site/src/components/cite/IncidentCard.js
  site/gatsby-site/src/components/cite/IncidentStatsCard.js
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/components/discover/Actions.js
  site/gatsby-site/src/components/taxa/Taxonomy.js
  site/gatsby-site/src/components/ui/WebArchiveLink.js
  site/gatsby-site/src/components/visualizations/Timeline.js
  site/gatsby-site/src/custom.css
  site/gatsby-site/src/elements/Card/index.js
  site/gatsby-site/src/elements/Col/index.js
  site/gatsby-site/src/elements/Container/index.js
  site/gatsby-site/src/elements/Pagination/index.js
  site/gatsby-site/src/elements/Row/index.js
  site/gatsby-site/src/elements/Tooltip/index.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/hooks/useModal.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/utils/cloudinary.js
  site/gatsby-site/tailwind.config.js
Labels: Type:Enhancement, PR:Needs Review, Stack:Front End

#926 Feature/tailwind discover
  site/gatsby-site/.eslintrc.json
  site/gatsby-site/cypress/e2e/discover.cy.js
  site/gatsby-site/jsconfig.json
  site/gatsby-site/src/components/LayoutHideSidebar.js
  site/gatsby-site/src/components/discover/Controls.js
  site/gatsby-site/src/components/discover/Hits.js
  site/gatsby-site/src/components/discover/OptionsModal.js
  site/gatsby-site/src/components/discover/Pagination.js
  site/gatsby-site/src/components/discover/SearchBox.js
  site/gatsby-site/src/components/forms/SearchInput.js
  site/gatsby-site/src/custom.css
  site/gatsby-site/src/elements/Col/index.js
  site/gatsby-site/src/elements/Container/index.js
  site/gatsby-site/src/elements/Row/index.js
  site/gatsby-site/src/hooks/useModal.js
  site/gatsby-site/src/pages/apps/discover.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: Type:Enhancement, PR:Needs Review, Stack:Front End

#788 Classification column filters
  site/gatsby-site/migrations/2022.08.15T19.33.01.remove-commas-in-classifications.js
  site/gatsby-site/src/pages/apps/classifications.js
Labels: PR:Needs Review

#894 Show related incidents below input
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/SemanticallyRelatedIncidents.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
Labels: PR:Needs Review

#862 Feature/tailwind landing page
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/LayoutHideSidebar.js
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/forms/SearchInput.js
  site/gatsby-site/src/components/landing/AboutDatabase .js
  site/gatsby-site/src/components/landing/Blog.js
  site/gatsby-site/src/components/landing/Featured.js
  site/gatsby-site/src/components/landing/Hero.js
  site/gatsby-site/src/components/landing/LatestReports.js
  site/gatsby-site/src/components/landing/Leaderboards.js
  site/gatsby-site/src/components/landing/QuickAdd.js
  site/gatsby-site/src/components/landing/QuickSearch.js
  site/gatsby-site/src/components/landing/RandomReports.js
  site/gatsby-site/src/components/landing/Sponsors.js
  site/gatsby-site/src/components/landing/WordCounts.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/elements/Card/index.js
  site/gatsby-site/src/elements/Form/index.js
  site/gatsby-site/src/elements/StyledImage/index.js
  site/gatsby-site/src/elements/StyledTitle/index.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/landingPage.js
  site/gatsby-site/tailwind.config.js
Labels: Type:Enhancement, PR:Needs Review, Stack:Front End

#989 Apply tailwind to footer
  site/gatsby-site/src/components/layout/Footer.js
  site/gatsby-site/src/tailwind.css
Labels: Type:Enhancement, PR:Needs Review, Stack:Front End

#990 Add title as required field in incidents schema
  site/realm/data_sources/mongodb-atlas/aiidprod/incidents/schema.json
Labels: PR:Needs Review

#978 Feature/tailwind top banner
  site/gatsby-site/src/components/ui/Header.js
  site/gatsby-site/src/tailwind.css
Labels: Type:Enhancement, PR:Needs Review, Stack:Front End

#805 Add description, developer, deployer and harmed parties fields
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/cypress/fixtures/submissions/submitted.json
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/graphql/submissions.js
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
  site/realm/functions/promoteSubmissionToReport.js
Labels: Type:Enhancement, PR:Needs Review, Stack:Front End, Stack:Back End

#779 Add TSNE Visualization
  site/gatsby-site/config.js
  site/gatsby-site/cypress/e2e/tsneVisualization.cy.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/netlify.toml
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/page-creators/createCitationPages.js
  site/gatsby-site/page-creators/createTsneVisualizationPage.js
  site/gatsby-site/src/api/semanticallyRelated.js
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/SemanticallyRelatedIncidents.js
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/graphql/incidents.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/tsneVisualizationPage.js
  site/gatsby-site/src/utils/updateTsne.js
  site/realm/data_sources/mongodb-atlas/aiidprod/incidents/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
  site/realm/functions/promoteSubmissionToReport.js
Labels: PR:Needs Review

#1003 Add Algolia as In-kind Sponsor
  site/gatsby-site/src/components/landing/Sponsors.js
  site/gatsby-site/src/components/landing/sponsors.json
  site/gatsby-site/src/elements/StyledImage/index.js
  site/gatsby-site/src/elements/StyledTitle/index.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/static/images/Algolia-nebula.svg
  site/gatsby-site/static/images/cloudinary_cloud_glyph_regular.svg
  site/gatsby-site/static/images/netlify-dark.svg
  site/gatsby-site/static/images/partership-on-ai-logo.png
  site/gatsby-site/static/images/wu-foundation-blue-logo.svg
Labels: PR:Needs Review, Stack:Front End

#1016 Fix SimilarIncidents styling
  site/gatsby-site/page-creators/createCitationPages.js
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1018 Prevent horizontal scrolling past body
  site/gatsby-site/src/components/LayoutHideSidebar.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Mergeable

#993 Use incident titles instead of report titles
  site/gatsby-site/src/components/landing/RandomIncidentsCarousel.js
  site/gatsby-site/src/pages/summaries/incidents.js
Labels: PR:Needs Review

#983 Submission length
  site/gatsby-site/i18n/locales/es/validation.json
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
Labels: PR:Work Needed
