Repository responsible-ai-collaborative/aiid, pull requests merged in 2022-12, with the labels that each got.

#1440 Add missing tags to submissions and reports
  site/gatsby-site/migrations/2022.11.30T23.39.58.fix-tags.js
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
Labels: PR:Mergeable

#1424 Use flowbite modal for submission modal
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1363 Change wizard buttons to two-lines, fix popover text
  site/gatsby-site/i18n/locales/en/popovers.json
  site/gatsby-site/i18n/locales/es/submit.json
  site/gatsby-site/i18n/locales/fr/submit.json
  site/gatsby-site/i18n/locales/fr/validation.json
  site/gatsby-site/src/components/forms/SubmissionWizard/StepContainer.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepThree.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepTwo.js
  site/gatsby-site/src/components/forms/TagsInputGroup.js
  site/gatsby-site/src/components/incidents/IncidentIdField.js
  site/gatsby-site/src/components/submissions/SubmissionWizard.js
Labels: PR:Needs Review

#1410 Move Incident updates notifications to post-build
  README.md
  site/gatsby-site/cypress/e2e/functions/onIncidentUpdate.cy.js
  site/gatsby-site/cypress/e2e/functions/processNotifications.cy.js
  site/realm/functions/onIncidentUpdate.js
  site/realm/functions/processNotifications.js
Labels: PR:Needs Review, Stack:Back End

#1348 Improve subscription flow
  site/gatsby-site/cypress/e2e/signup.cy.js
  site/gatsby-site/i18n/locales/es/login.json
  site/gatsby-site/i18n/locales/fr/login.json
  site/gatsby-site/src/pages/signup.js
Labels: PR:Needs Review

#1443 Fix/incident reports title
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1416 Fix image report
  site/gatsby-site/cypress/e2e/apps/submitted.cy.js
  site/gatsby-site/cypress/e2e/citeEdit.cy.js
  site/gatsby-site/cypress/fixtures/submissions/submitted.json
  site/gatsby-site/migrations/2022.11.30T19.51.52.fix-report-images.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: Type:Bug, PR:Needs Review

#1458 Move right sidebar on /cite
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1442 Fix/entities link
  site/gatsby-site/cypress/e2e/apps/incidents.cy.js
  site/gatsby-site/src/components/incidents/IncidentsTable.js
Labels: PR:Work Needed

#1327 Add editor's guide
  site/gatsby-site/config.js
  site/gatsby-site/content/editors-guide/index.es.mdx
  site/gatsby-site/content/editors-guide/index.fr.mdx
  site/gatsby-site/content/editors-guide/index.mdx
  site/gatsby-site/src/global.css
Labels: PR:Needs Review

#1445 Feature/back btn incidents
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/pages/incidents/edit.js
  site/gatsby-site/src/templates/cite.js
Labels: PR:Mergeable

#1482 Prevent wrapping inside badges
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/entities/AllegedEntities.js
Labels: PR:Needs Review

#1446 Feature/empty alt submit
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1462 Add confirmation to delete quick-add url
  site/gatsby-site/i18n/locales/es/submitted.json
  site/gatsby-site/i18n/locales/fr/submitted.json
  site/gatsby-site/src/pages/apps/submitted.js
Labels: PR:Needs Review

#1444 Add skeletons on large loading sections
  site/gatsby-site/src/components/discover/Hits.js
  site/gatsby-site/src/components/submissions/SubmissionList.js
  site/gatsby-site/src/elements/Skeletons/Card/index.js
  site/gatsby-site/src/elements/Skeletons/Default/index.js
  site/gatsby-site/src/elements/Skeletons/List/index.js
  site/gatsby-site/src/pages/apps/classifications.js
  site/gatsby-site/src/pages/apps/incidents.js
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/pages/apps/submitted.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/pages/incidents/edit.js
Labels: PR:Needs Review

#1422 Fix/Submission Form: hide description when incident id
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepThree.js
Labels: PR:Needs Review

#1414 Redesign cite report cards
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/reports/ReportCard.js
Labels: PR:Needs Review

#1438 Fix form issues
  site/gatsby-site/cypress/e2e/integration/incidents.cy.js
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/cypress/e2e/unit/functions/promoteSubmissionToReport.cy.js
  site/gatsby-site/cypress/fixtures/incidents/incident.json
  site/gatsby-site/src/components/forms/SubmissionWizard/StepThree.js
  site/gatsby-site/src/components/incidents/IncidentForm.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/schemas.js
  site/gatsby-site/src/graphql/submissions.js
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
  site/realm/functions/promoteSubmissionToReport.js
Labels: PR:Needs Review
