Repository responsible-ai-collaborative/aiid, pull requests merged in 2023-08, with the labels that each got.

#2185 Add `LogHistoryContext` and refactor log history functions
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/components/discover/Actions.js
  site/gatsby-site/src/components/incidents/IncidentEditModal.js
  site/gatsby-site/src/hooks/useLogIncidentHistory.js
  site/gatsby-site/src/hooks/useLogReportHistory.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/pages/incidents/edit.js
Labels: PR:Needs Review

#2215 Update schema to handle classifications linking to multiple incidents and/or reports
  site/gatsby-site/cypress/e2e/integration/apps/csettool.cy.js
  site/gatsby-site/cypress/e2e/integration/integrity.cy.js
  site/gatsby-site/cypress/e2e/unit/AlgoliaUpdater.cy.js
  site/gatsby-site/cypress/fixtures/call/classifications.json
  site/gatsby-site/cypress/fixtures/classifications/cssettool.json
  site/gatsby-site/cypress/fixtures/classifications/incident97Classifications.json
  site/gatsby-site/cypress/fixtures/classifications/upsertCSET.json
  site/gatsby-site/cypress/fixtures/classifications/upsertCSETv1merge.json
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/migrations/2023.07.24T22.00.41.classifications-incidents-reports.js
  site/gatsby-site/page-creators/createTsneVisualizationPage.js
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/components/classifications/CsetTable.js
  site/gatsby-site/src/components/taxa/TaxonomyForm.js
  site/gatsby-site/src/contexts/userContext/UserContextProvider.js
  site/gatsby-site/src/graphql/classifications.js
  site/gatsby-site/src/pages/apps/classifications.js
  site/gatsby-site/src/pages/apps/csettool/{mongodbAiidprodIncidents.incident_id}.js
  site/gatsby-site/src/pages/summaries/cset-charts.js
  site/gatsby-site/src/pages/taxonomies.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/citeDynamicTemplate.js
  site/gatsby-site/src/templates/taxonomy.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
  site/realm/data_sources/mongodb-atlas/aiidprod/classifications/relationships.json
  site/realm/data_sources/mongodb-atlas/aiidprod/classifications/schema.json
Labels: PR:Needs Review

#2230 Fix "Should clone an incident" test
  site/gatsby-site/cypress/e2e/integration/incidents/new.cy.js
Labels: Type:Bug, PR:Needs Review, Priority:High

#2216 Add Incident Version History page
  site/gatsby-site/cypress/e2e/integration/incidents/history.cy.js
  site/gatsby-site/cypress/fixtures/history/incidentHistory.json
  site/gatsby-site/migrations/2023.08.10T19.09.35.create-first-history-version.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/cite/Tools.js
  site/gatsby-site/src/graphql/entities.js
  site/gatsby-site/src/graphql/incidents.js
  site/gatsby-site/src/pages/incidents/history.js
  site/gatsby-site/src/utils/cite.js
Labels: PR:Needs Review

#2238 Migration: remove BNH from report submitter names
  site/gatsby-site/migrations/2023.08.14T15.28.31.migration-bnh-submissions.js
Labels: PR:Needs Review

#2239 Fix reports with `user == undefined`
  site/gatsby-site/cypress/e2e/unit/functions/promoteSubmissionToReport.cy.js
  site/gatsby-site/migrations/2023.08.17T15.56.33.fix-report-users.js
  site/realm/functions/promoteSubmissionToReport.js
Labels: Type:Bug, PR:Needs Review, Priority:High

#2245 Add migration to unset null `user` values from `history.reports`
  site/gatsby-site/migrations/2023.08.19T00.17.14.fix-report-history-users.js
Labels: PR:Needs Review

#2233 Add `Restore Version` button on Incident History page
  site/gatsby-site/cypress/e2e/integration/incidents/history.cy.js
  site/gatsby-site/cypress/fixtures/history/incidentHistory.json
  site/gatsby-site/src/pages/incidents/history.js
  site/gatsby-site/src/utils/cite.js
Labels: PR:Needs Review

#2261 Don't restore the `user` report field
  site/gatsby-site/cypress/e2e/integration/reportHistory.cy.js
  site/gatsby-site/cypress/fixtures/history/reportHistory.json
  site/gatsby-site/src/pages/cite/history.js
  site/gatsby-site/src/pages/incidents/history.js
Labels: Type:Bug, PR:Needs Review

#2249 Fix empty report title in related incidents
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
Labels: PR:Needs Review
