Repository responsible-ai-collaborative/aiid, pull requests merged in 2023-05, with the labels that each got.

#1941 Fix classifications page layout
  site/gatsby-site/cypress/e2e/integration/taxonomy/cset.cy.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/pages/apps/classifications.js
Labels: PR:Needs Review

#1956 Approved variants will be first in the list
  site/gatsby-site/src/components/variants/VariantList.js
  site/gatsby-site/src/components/variants/VariantsTable.js
Labels: PR:Mergeable

#1953 Add Variant condition to `linkReportsToIncidents` function
  site/gatsby-site/cypress/e2e/unit/functions/linkReportsToIncidents.cy.js
  site/gatsby-site/migrations/2023.05.03T19.04.47.update-variants-with-flag.js
  site/realm/functions/linkReportsToIncidents.js
Labels: PR:Needs Review

#1958 Add more tests to `incidentEditModal` component
  site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
  site/gatsby-site/src/components/incidents/IncidentEditModal.js
Labels: PR:Mergeable

#1950 Upgrade Cloudinary package and add lazy loading
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/PlaceholderImage.js
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/components/discover/hitTypes/Compact.js
  site/gatsby-site/src/components/entities/CommonEntities.js
  site/gatsby-site/src/components/forms/PreviewImageInputGroup.js
  site/gatsby-site/src/components/landing/Featured.js
  site/gatsby-site/src/components/landing/RandomIncidentsCarousel.js
  site/gatsby-site/src/components/ui/Header.js
  site/gatsby-site/src/elements/StyledImage/index.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Mergeable

#1923 Fix/filters wrap
  site/gatsby-site/src/components/discover/Filter.js
  site/gatsby-site/src/components/discover/Filters.js
Labels: PR:Mergeable

#1778 Fix discover page warnings
  site/gatsby-site/src/components/discover/DisplayModeSwitch.js
  site/gatsby-site/src/components/discover/SORTING_LISTS.js
  site/gatsby-site/src/components/sidebar/tree.js
Labels: PR:Work Needed

#1971 Improve translations of improv blog post in FR
  site/gatsby-site/blog/improv-ai/index.fr.mdx
Labels: PR:Needs Review

#1954 Fix similar incident cards on smaller resolutions
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1942 Submit/fallback image warning
  site/gatsby-site/i18n/locales/en/popovers.json
  site/gatsby-site/i18n/locales/es/popovers.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/popovers.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/forms/PreviewImageInputGroup.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1907 Feature/tables consistency
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/incidents/IncidentsTable.js
  site/gatsby-site/src/components/ui/Table.js
  site/gatsby-site/src/components/variants/VariantsTable.js
  site/gatsby-site/src/pages/apps/classifications.js
  site/gatsby-site/src/pages/apps/reports.js
Labels: PR:Needs Review

#1992 Add missing `text` field on Variants query
  site/gatsby-site/src/graphql/variants.js
Labels: PR:Mergeable

#1987 Remove unused packages and files
  site/gatsby-site/.eslintrc.json
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/gatsby-shared.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/IncidentList.js
  site/gatsby-site/src/components/TaxonomiesList.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepFour.js
  site/gatsby-site/src/components/incidents/IncidentIdField.js
  site/gatsby-site/src/components/theme/index.js
  site/gatsby-site/src/components/theme/themeProvider.js
  site/gatsby-site/src/elements/StyledTitle/index.js
  site/gatsby-site/src/elements/Tooltip/index.js
  site/gatsby-site/src/elements/Wizard/index.js
  site/gatsby-site/src/hooks/useMongo.js
  site/gatsby-site/src/queries/classifications.js
  site/gatsby-site/src/utils/algolia.js
Labels: PR:Mergeable

#1996 Fix bug when we search by text and then filter on Discover
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/src/pages/apps/discover.js
Labels: Type:Bug, PR:Mergeable, Priority:High

#1960 Add editor's story blog post
  site/gatsby-site/blog/editors-story/images/editors.png
  site/gatsby-site/blog/editors-story/images/image1.png
  site/gatsby-site/blog/editors-story/images/image2.jpg
  site/gatsby-site/blog/editors-story/images/image3.png
  site/gatsby-site/blog/editors-story/images/image4.png
  site/gatsby-site/blog/editors-story/index.es.mdx
  site/gatsby-site/blog/editors-story/index.fr.mdx
  site/gatsby-site/blog/editors-story/index.mdx
  site/gatsby-site/src/components/ui/MdxComponents.js
Labels: PR:Needs Review

#2001 Fix wordcount repeated words
  site/gatsby-site/src/templates/wordcounts.js
Labels: PR:Mergeable

#1994 Remove unused Allowed Origin URLs
  site/realm/realm_config.json
Labels: PR:Needs Review

#1955 Make titlewrapper align with quick action buttons
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/global.css
  site/gatsby-site/src/pages/account.js
  site/gatsby-site/src/pages/apps/newsdigest.js
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/pages/apps/submitted.js
  site/gatsby-site/src/pages/blog/index.js
  site/gatsby-site/src/pages/summaries/flagged.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/pages/summaries/leaderboard.js
  site/gatsby-site/src/pages/taxonomies.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/backups.js
  site/gatsby-site/src/templates/cite-duplicate.js
  site/gatsby-site/src/templates/citeTemplate.js
  site/gatsby-site/src/templates/doc.js
  site/gatsby-site/src/templates/entities.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/templates/post.js
  site/gatsby-site/src/templates/taxonomy.js
  site/gatsby-site/src/templates/tsneVisualizationPage.js
  site/gatsby-site/src/templates/wordcounts.js
Labels: PR:Needs Review

#2011 Display floating collapse button on cite
  site/gatsby-site/src/components/reports/ReportCard.js
Labels: PR:Mergeable

#1924 Improve scroll to top on form
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/submissions/SubmissionWizard.js
Labels: PR:Needs Review

#1943 Replace wordcounts with email form
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/forms/TextInputGroup.js
  site/gatsby-site/src/components/landing/NewsletterSignup.js
  site/gatsby-site/src/images/neural-net-envelope.png
  site/gatsby-site/src/pages/signup.js
  site/gatsby-site/src/templates/landingPage.js
Labels: PR:Needs Review

#2034 Add april roundup blog post and its translations
  site/gatsby-site/blog/incident-report-2023-april/images/aiid-april.png
  site/gatsby-site/blog/incident-report-2023-april/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-april/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-april/index.mdx
Labels: PR:Mergeable

#2051 Fix/edit report issues
  site/gatsby-site/cypress/e2e/integration/apps/submitted.cy.js
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/src/components/cite/Tools.js
  site/gatsby-site/src/components/incidents/IncidentsField.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
Labels: PR:Mergeable

#2028 feature/similar incidents improvements
  site/gatsby-site/src/components/cite/SimilarIncidents.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Mergeable

#2042 Make random incidents carousel's arrows more visible
  site/gatsby-site/src/components/cite/ImageCarousel.js
  site/gatsby-site/src/components/landing/RandomIncidentsCarousel.js
Labels: PR:Needs Review

#2032 Reuse report card component in list view
  site/gatsby-site/src/components/discover/Actions.js
  site/gatsby-site/src/components/discover/hitTypes/List.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/templates/citeTemplate.js
  site/gatsby-site/src/templates/report.js
Labels: PR:Needs Review

#2035 Feature/tax exempt forms
  site/gatsby-site/i18n/locales/es/landing.json
  site/gatsby-site/i18n/locales/fr/landing.json
  site/gatsby-site/src/components/landing/Sponsors.js
Labels: PR:Needs Review
