Repository responsible-ai-collaborative/aiid, pull requests merged in 2023-04, with the labels that each got.

#1813 Fix summaries incidents large buttons
  site/gatsby-site/src/pages/summaries/incidents.js
Labels: PR:Needs Review

#1782 Remove bootstrap from forms
  site/gatsby-site/cypress/e2e/integration/apps/submitted.cy.js
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/Label.js
  site/gatsby-site/src/components/forms/QuickAddForm.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/forms/TextInputGroup.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1819 Fix cloudinary fallback logic
  site/gatsby-site/src/components/cite/ImageCarousel.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1823 Improve cloudinary placeholder check
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1828 Cloudinary images edge cases
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1817 Fix prev/next incident buttons for dynamic page
  site/gatsby-site/src/pages/cite/[id].js
Labels: PR:Needs Review

#1816 Remove bootstrap from signup/login components
  site/gatsby-site/src/components/forms/TextInputGroup.js
  site/gatsby-site/src/pages/forgotpassword.js
  site/gatsby-site/src/pages/login.js
  site/gatsby-site/src/pages/resetpassword.js
  site/gatsby-site/src/pages/signup.js
Labels: PR:Needs Review

#1795 TaxonomyForm: add deselect to radio buttons, support duplicate fields
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/src/components/taxa/TaxonomyForm.js
Labels: PR:Needs Review

#1832 Remove bootstrap from reports, backups and cite-duplicate pages
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/backups.js
  site/gatsby-site/src/templates/cite-duplicate.js
Labels: PR:Needs Review

#1748 User Management
  site/gatsby-site/cypress/e2e/incidentVariants.cy.js
  site/gatsby-site/cypress/e2e/integration/admin.cy.js
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/cypress/e2e/unit/functions/apiRequest.cy.js
  site/gatsby-site/src/components/entities/EntitiesTable.js
  site/gatsby-site/src/components/ui/SubmitButton.js
  site/gatsby-site/src/components/ui/Table.js
  site/gatsby-site/src/components/users/UserEditModal.js
  site/gatsby-site/src/components/users/UserForm.js
  site/gatsby-site/src/components/users/UsersTable.js
  site/gatsby-site/src/contexts/userContext/UserContextProvider.js
  site/gatsby-site/src/graphql/users.js
  site/gatsby-site/src/pages/admin/index.js
  site/realm/data_sources/mongodb-atlas/config.json
  site/realm/data_sources/mongodb-atlas/customData/users/rules.json
  site/realm/functions/apiRequest.js
  site/realm/functions/config.json
  site/realm/functions/getUser.js
  site/realm/functions/getUserAdminData.js
  site/realm/graphql/custom_resolvers/user_adminData.json
Labels: PR:Work Needed

#1831 Fix user email confirmation
  site/gatsby-site/cypress/e2e/integration/confirmemail.cy.js
  site/gatsby-site/src/pages/confirmemail.js
Labels: PR:Needs Review

#1825 Remove bootstrap and styled components from classification page
  site/gatsby-site/src/pages/apps/classifications.js
Labels: PR:Needs Review

#1858 Remove bootstrap & styled-components from toast component
  site/gatsby-site/cypress/e2e/integration/citeEdit.cy.js
  site/gatsby-site/cypress/e2e/integration/incidents/edit.cy.js
  site/gatsby-site/cypress/e2e/integration/landingPage.cy.js
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/contexts/ToastContext.js
  site/gatsby-site/src/hooks/useToast.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/citeTemplate.js
  site/gatsby-site/tailwind.config.js
Labels: PR:Mergeable

#1851 Fix/bootstrap timeline
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/discover/filterTypes/RangeInput.js
  site/gatsby-site/src/components/discover/filterTypes/RefinementList.js
  site/gatsby-site/src/components/discover/hitTypes/shared.js
  site/gatsby-site/src/components/incidents/IncidentsTable.js
  site/gatsby-site/src/components/visualizations/Timeline.js
  site/gatsby-site/src/templates/taxonomy.js
Labels: PR:Mergeable

#1869 Add March roundup blog post
  site/gatsby-site/blog/incident-report-2023-march/images/aiid-march.webp
  site/gatsby-site/blog/incident-report-2023-march/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.mdx
Labels: PR:Needs Review

#1864 Fix GMF potential failure definition
  site/gatsby-site/migrations/2023.04.13T18.02.55.fix-gmf-potential-failure-definition.js
Labels: PR:Needs Review

#1881 Fix/Code markdown in cards
  site/gatsby-site/src/components/reports/ReportText.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Mergeable

#1884 Submission leaderboards displayed side-by-side
  site/gatsby-site/src/components/leaderboards/AuthorsLeaderboard.js
  site/gatsby-site/src/components/leaderboards/DomainsLeaderboard.js
  site/gatsby-site/src/components/leaderboards/OriginalSubmittersLeaderboard.js
  site/gatsby-site/src/components/leaderboards/SubmittersLeaderboard.js
  site/gatsby-site/src/components/leaderboards/UniqueSubmittersLeaderboard.js
  site/gatsby-site/src/pages/summaries/leaderboard.js
Labels: PR:Mergeable

#1890 CSETv1 Bugs
  site/gatsby-site/src/components/taxa/TaxonomyForm.js
Labels: PR:Needs Review

#1892 Translate march roundup blog post
  site/gatsby-site/blog/incident-report-2022-november/index.es.mdx
  site/gatsby-site/blog/incident-report-2022-november/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-february/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-february/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-january/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-january/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.mdx
  site/gatsby-site/blog/multilingual-incident-reporting/index.es.mdx
Labels: PR:Needs Review

#1882 Complete removal of react-bootstrap and styled-components
  site/gatsby-site/cypress/e2e/integration/citeEdit.cy.js
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/gatsby-browser.js
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/gatsby-shared.js
  site/gatsby-site/gatsby-ssr.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/bootstrap.scss
  site/gatsby-site/src/components/IncidentList.js
  site/gatsby-site/src/components/discover/hitTypes/Details.js
  site/gatsby-site/src/components/discover/hitTypes/shared.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/incidents/IncidentsField.js
  site/gatsby-site/src/components/leaderboards/Leaderboard.js
  site/gatsby-site/src/components/theme/themeProvider.js
  site/gatsby-site/src/components/ui/Loader.js
  site/gatsby-site/src/components/ui/WebArchiveLink.js
  site/gatsby-site/src/components/variants/VariantEditModal.js
  site/gatsby-site/src/elements/PopoverWrapper/index.js
  site/gatsby-site/src/hooks/useModal.js
  site/gatsby-site/src/pages/404.js
  site/gatsby-site/src/pages/apps/classifications.js
  site/gatsby-site/src/pages/incidents/edit.js
  site/gatsby-site/src/pages/logout.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/taxonomy.js
Labels: PR:Needs Review

#1850 Add `Show Live data` toogle button on `cite` page
  site/gatsby-site/cypress/e2e/integration/dynamicCite.cy.js
  site/gatsby-site/cypress/fixtures/incidents/incident10.json
  site/gatsby-site/src/components/variants/VariantList.js
  site/gatsby-site/src/graphql/variants.js
  site/gatsby-site/src/pages/cite/[id].js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/citeDynamicTemplate.js
  site/gatsby-site/src/templates/citeTemplate.js
Labels: PR:Needs Review

#1844 Feature/image tests
  site/gatsby-site/cypress/e2e/integration/pages.cy.js
  site/gatsby-site/src/components/PlaceholderImage.js
  site/gatsby-site/src/utils/cloudinary.js
Labels: PR:Needs Review

#1908 Move Live Data button to the Tools Incident section
  site/gatsby-site/src/components/cite/Tools.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/citeDynamicTemplate.js
  site/gatsby-site/src/templates/citeTemplate.js
Labels: PR:Needs Review

#1898 Restore outline in blog
  site/gatsby-site/cypress/e2e/integration/blog.cy.js
  site/gatsby-site/src/components/Outline.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1913 Incident Page – Fix bullet point visual bug
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1918 Only display `Live data` for `incident_editor`, `taxonomy_editor` and `admin` roles
  site/gatsby-site/cypress/e2e/integration/dynamicCite.cy.js
  site/gatsby-site/src/components/cite/Tools.js
Labels: PR:Needs Review

#1905 Translate improv post
  site/gatsby-site/blog/improv-ai/index.es.mdx
  site/gatsby-site/blog/improv-ai/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.mdx
Labels: PR:Mergeable

#1899 Remove url-encoding from March blog post link
  site/gatsby-site/blog/incident-report-2023-march/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-march/index.mdx
Labels: PR:Needs Review

#1876 Fix spatial view initial view and selected color
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1887 Remove CSET publish field
  site/gatsby-site/migrations/2023.04.17T23.15.19.remove-cset-publish-field.js
Labels: PR:Needs Review

#1921 Change leaderboard page layout
  site/gatsby-site/i18n/locales/es/landing.json
  site/gatsby-site/i18n/locales/fr/landing.json
  site/gatsby-site/src/components/leaderboards/Leaderboard.js
  site/gatsby-site/src/components/leaderboards/OriginalSubmittersLeaderboard.js
  site/gatsby-site/src/components/leaderboards/SubmittersLeaderboard.js
  site/gatsby-site/src/components/leaderboards/UniqueSubmittersLeaderboard.js
  site/gatsby-site/src/pages/summaries/leaderboard.js
Labels: PR:Mergeable

#1928 Add indexes as recommended by mongodb profiler
  site/gatsby-site/migrations/2023.04.24T20.20.43.add-indexes.js
Labels: PR:Mergeable

#1938 Add Newsweek article to landing
  site/gatsby-site/src/components/landing/Featured.js
  site/gatsby-site/static/images/news/newsweek.svg
Labels: PR:Needs Review

#1932 Add last page button to Table component
  site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
  site/gatsby-site/src/components/ui/Table.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: PR:Mergeable

#1922 Improve Typeahead
  site/gatsby-site/src/tailwind.css
Labels: PR:Needs Review

#1920 Keep taxonomy menus open for multiple selection
  site/gatsby-site/src/components/forms/Tags.js
  site/gatsby-site/src/components/taxa/TaxonomyForm.js
Labels: PR:Needs Review

#1935 Fix taxonomy graph carousel switching
  site/gatsby-site/src/components/TaxonomyGraphCarousel.js
  site/gatsby-site/src/templates/taxonomy.js
Labels: PR:Needs Review

#1835 Add autocomplete to entities on submission form
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepThree.js
  site/gatsby-site/src/components/forms/TagsControl.js
  site/gatsby-site/src/components/forms/TagsInputGroup.js
Labels: PR:Needs Review

#1793 New Incident Variants UX
  site/gatsby-site/cypress/e2e/incidentVariants.cy.js
  site/gatsby-site/cypress/e2e/integration/apps/variants.cy.js
  site/gatsby-site/cypress/e2e/integration/dynamicCite.cy.js
  site/gatsby-site/cypress/e2e/integration/pages.cy.js
  site/gatsby-site/cypress/e2e/unit/functions/onIncidentUpdate.cy.js
  site/gatsby-site/cypress/fixtures/incidents/incident10.json
  site/gatsby-site/cypress/fixtures/variants/variants.json
  site/gatsby-site/cypress/fixtures/variants/variantsIncident.json
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/i18n/locales/en/popovers.json
  site/gatsby-site/i18n/locales/es/popovers.json
  site/gatsby-site/i18n/locales/es/variants.json
  site/gatsby-site/i18n/locales/fr/popovers.json
  site/gatsby-site/i18n/locales/fr/variants.json
  site/gatsby-site/migrations/2023.04.05T20.46.18.move-text-inputs-outputs-fields.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/components/variants/VariantEditModal.js
  site/gatsby-site/src/components/variants/VariantForm.js
  site/gatsby-site/src/components/variants/VariantList.js
  site/gatsby-site/src/components/variants/VariantsTable.js
  site/gatsby-site/src/graphql/incidents.js
  site/gatsby-site/src/graphql/reports.js
  site/gatsby-site/src/graphql/variants.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/utils/variants.js
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/rules.json
  site/realm/data_sources/mongodb-atlas/aiidprod/reports/schema.json
  site/realm/functions/createVariant.js
  site/realm/functions/onIncidentUpdate.js
  site/realm/graphql/custom_resolvers/mutation_createVariant.json
Labels: PR:Needs Review
