Repository responsible-ai-collaborative/aiid, pull requests merged in 2023-03, with the labels that each got.

#1669 Hotfix: Give entity insert and write permissions to default user
  site/realm/data_sources/mongodb-atlas/aiidprod/entities/rules.json
Labels: PR:Mergeable

#1649 Improve Rollbar error handling
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/incidents/IncidentEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionEditModal.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/components/submissions/SubmissionWizard.js
  site/gatsby-site/src/components/taxa/TaxonomyForm.js
  site/gatsby-site/src/components/variants/VariantEditModal.js
  site/gatsby-site/src/components/variants/VariantList.js
  site/gatsby-site/src/components/variants/VariantsTable.js
  site/gatsby-site/src/contexts/ToastContext.js
  site/gatsby-site/src/contexts/userContext/UserContextProvider.js
  site/gatsby-site/src/pages/apps/submitted.js
  site/gatsby-site/src/pages/cite/edit.js
  site/gatsby-site/src/pages/forgotpassword.js
  site/gatsby-site/src/pages/incidents/edit.js
  site/gatsby-site/src/pages/resetpassword.js
  site/gatsby-site/src/pages/signup.js
  site/gatsby-site/src/pages/unsubscribe.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/static/rollbar.js
Labels: Type:Enhancement, PR:Needs Review

#1585 Fix issue when submitting multiple forms in a row
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/forms/SubmitForm.js
Labels: PR:Needs Review

#1655 Save sortBy in URL and use that param to sort
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/src/components/discover/ClearFilters.js
  site/gatsby-site/src/components/discover/Controls.js
  site/gatsby-site/src/components/discover/SORTING_LISTS.js
  site/gatsby-site/src/components/discover/Sorting.js
  site/gatsby-site/src/components/discover/queryParams.js
  site/gatsby-site/src/pages/apps/discover.js
Labels: PR:Mergeable

#1666 Improve incident table page performance
  site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
  site/gatsby-site/src/components/incidents/IncidentsTable.js
  site/gatsby-site/src/graphql/incidents.js
Labels: PR:Work Needed

#1702 Translate January roundup blog post to spanish and french
  site/gatsby-site/blog/incident-report-2023-january/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-january/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-january/index.mdx
Labels: PR:Mergeable

#1681 CSETv1 update 2
  site/gatsby-site/migrations/2023.03.02T17.56.54.csetv1-update-2.js
Labels: PR:Needs Review

#1699 Fix date-related hydration errors
  site/gatsby-site/blog/incident-report-2023-january/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-january/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-january/index.mdx
  site/gatsby-site/cypress/e2e/integration/errors.cy.js
  site/gatsby-site/cypress/e2e/integration/pages.cy.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/landing/AboutDatabase .js
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
  site/gatsby-site/src/components/ui/DateLabel.js
  site/gatsby-site/src/contexts/ToastContext.js
  site/gatsby-site/src/pages/confirmemail.js
  site/gatsby-site/src/pages/summaries/flagged.js
  site/gatsby-site/src/pages/unsubscribe.js
  site/gatsby-site/src/templates/landingPage.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Mergeable

#1507 Fix navigation tests
  site/gatsby-site/config.js
  site/gatsby-site/cypress/e2e/integration/confirmemail.cy.js
  site/gatsby-site/cypress/e2e/integration/navigation.cy.js
  site/gatsby-site/src/components/loginSignup/index.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/components/sidebar/tree.js
  site/gatsby-site/src/components/sidebar/treeNode.js
  site/gatsby-site/src/pages/confirmemail.js
  site/gatsby-site/src/pages/login.js
Labels: PR:Needs Review

#1629 Add export to CSV option to Discover page
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/src/components/discover/Controls.js
  site/gatsby-site/src/components/discover/CsvExport.js
Labels: PR:Needs Review

#1701 Feature/Add tags and language in search filters
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/src/components/discover/Filter.js
  site/gatsby-site/src/components/discover/Filters.js
  site/gatsby-site/src/components/discover/REFINEMENT_LISTS.js
  site/gatsby-site/src/components/discover/queryParams.js
  site/gatsby-site/src/pages/apps/discover.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
  site/gatsby-site/src/utils/algoliaSettings.js
Labels: PR:Mergeable

#1696 Add ChatGPT in Controversy blog post
  site/gatsby-site/blog/chatgpt-incidents-and-issues/images/chatgpt-question-exclamation.png
  site/gatsby-site/blog/chatgpt-incidents-and-issues/index.es.mdx
  site/gatsby-site/blog/chatgpt-incidents-and-issues/index.fr.mdx
  site/gatsby-site/blog/chatgpt-incidents-and-issues/index.mdx
Labels: PR:Mergeable

#1317 News Digest Update
  site/gatsby-site/cypress/e2e/integration/apps/newsdigest.cy.js
  site/gatsby-site/cypress/e2e/integration/pages.cy.js
  site/gatsby-site/cypress/fixtures/candidates/newsArticles.json
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/src/elements/Skeletons/Card/index.js
  site/gatsby-site/src/pages/apps/newsSearch.js
  site/gatsby-site/src/pages/apps/newsdigest.js
  site/gatsby-site/tailwind.config.js
  site/realm/data_sources/mongodb-atlas/aiidprod/candidates/schema.json
Labels: PR:Needs Review

#1708 Default sorting to featured replica index
  site/gatsby-site/config.js
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/src/components/discover/ClearFilters.js
  site/gatsby-site/src/components/discover/DEFAULT_SEARCH_KEYS_VALUES.js
  site/gatsby-site/src/components/discover/Sorting.js
  site/gatsby-site/src/components/discover/hitTypes/Compact.js
  site/gatsby-site/src/components/discover/hitTypes/Details.js
  site/gatsby-site/src/components/discover/hitTypes/List.js
  site/gatsby-site/src/pages/apps/discover.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
Labels: PR:Needs Review

#1726 Fix index featured values so it matches config file
  site/gatsby-site/config.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
Labels: PR:Needs Review

#1731 Inconsistent vertical spacing in sort and filters on discover page
  site/gatsby-site/src/components/discover/Controls.js
Labels: PR:Mergeable

#1713 Fix/login redirect
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/loginSignup/index.js
  site/gatsby-site/src/components/sidebar/index.js
  site/gatsby-site/src/components/ui/Header.js
  site/gatsby-site/src/pages/signup.js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/entity.js
Labels: PR:Needs Review

#1693 Fix/latest report link
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
Labels: PR:Mergeable

#1716 Cite page -> Report Card title click should expand card
  site/gatsby-site/src/components/reports/ReportCard.js
Labels: PR:Needs Review

#1700 Fix blog index width
  site/gatsby-site/src/components/Layout.js
Labels: PR:Needs Review

#1720 Add live option to Incidents table page
  site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/incidents/IncidentsTable.js
  site/gatsby-site/src/graphql/incidents.js
  site/gatsby-site/src/pages/apps/incidents.js
Labels: PR:Needs Review

#1680 Feature/cite improvements
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/BibTex.js
  site/gatsby-site/src/components/cite/Citation.js
  site/gatsby-site/src/components/cite/CitationFormat.js
  site/gatsby-site/src/components/cite/ImageCarousel.js
  site/gatsby-site/src/components/cite/IncidentStatsCard.js
  site/gatsby-site/src/components/cite/NotifyButton.js
  site/gatsby-site/src/components/cite/Tools.js
  site/gatsby-site/src/components/cite/citationTypes/BibTex.js
  site/gatsby-site/src/components/cite/citationTypes/Citation.js
  site/gatsby-site/src/components/cite/citationTypes/index.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/cite.js
Labels: PR:Needs Review

#1727 Add copies of CSETv1 taxonomy for 3 annotators
  site/gatsby-site/migrations/2023.03.13T16.16.18.copy-csetv1-taxonomy.js
Labels: PR:Mergeable

#1742 Remove `skip` on all `incidentVariants` tests
  site/gatsby-site/cypress/e2e/incidentVariants.cy.js
Labels: PR:Needs Review

#1733 Feature/add mtf to landing
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/i18n/locales/en/sponsors.json
  site/gatsby-site/i18n/locales/es/sponsors.json
  site/gatsby-site/i18n/locales/fr/sponsors.json
  site/gatsby-site/src/components/landing/Sponsors.js
  site/gatsby-site/src/components/landing/sponsors.json
  site/gatsby-site/static/images/mtf-grand.svg
Labels: PR:Needs Review

#1425 Style Entity and Blog Post Headers
  site/gatsby-site/cypress/e2e/integration/entity.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/styles/Post.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Needs Review

#1740 Remove bootstrap/styled components from submitted page
  site/gatsby-site/cypress/e2e/integration/apps/submitted.cy.js
  site/gatsby-site/src/components/ReadMoreText.js
  site/gatsby-site/src/components/submissions/SubmissionList.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/pages/apps/submitted.js
Labels: PR:Needs Review

#1687 Add translation to collapsed sidebar
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/sidebar/treeNode.js
Labels: PR:Needs Review

#1667 Update to gatsby v5
  README.md
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/package-lock.json
  site/gatsby-site/package.json
  site/gatsby-site/page-creators/createWordCountsPage.js
  site/gatsby-site/src/api/graphql.js
  site/gatsby-site/src/components/landing/RandomIncidentsCarousel.js
  site/gatsby-site/src/components/leaderboards/AuthorsLeaderboard.js
  site/gatsby-site/src/components/leaderboards/DomainsLeaderboard.js
  site/gatsby-site/src/components/leaderboards/OriginalSubmittersLeaderboard.js
  site/gatsby-site/src/components/leaderboards/SubmittersLeaderboard.js
  site/gatsby-site/src/components/taxa/TaxonomyForm.js
  site/gatsby-site/src/pages/blog/index.js
  site/gatsby-site/src/pages/summaries/flagged.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/pages/summaries/incidentsOverTime.js
  site/gatsby-site/src/templates/landingPage.js
Labels: PR:Mergeable

#1746 Add February roundup
  site/gatsby-site/blog/incident-report-2023-february/images/aiid-february.webp
  site/gatsby-site/blog/incident-report-2023-february/index.es.mdx
  site/gatsby-site/blog/incident-report-2023-february/index.fr.mdx
  site/gatsby-site/blog/incident-report-2023-february/index.mdx
Labels: PR:Needs Review

#1760 Update config files to reflect what's stored on realm
  site/realm/data_sources/mongodb-atlas/aiidprod/candidates/rules.json
  site/realm/data_sources/mongodb-atlas/aiidprod/candidates/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/classifications/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/submissions/schema.json
  site/realm/data_sources/mongodb-atlas/aiidprod/taxa/schema.json
  site/realm/data_sources/mongodb-atlas/config.json
  site/realm/triggers/onIncidentUpdate.json
  site/realm/triggers/onNewIncident.json
Labels: PR:Mergeable

#1764 Remove bootstrap from EntitiesTable
  site/gatsby-site/src/components/entities/EntitiesTable.js
Labels: PR:Needs Review

#1762 Remove bootstrap/styled-components from incidents page (table view)
  site/gatsby-site/cypress/e2e/integration/incidents/edit.cy.js
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/Label.js
  site/gatsby-site/src/components/forms/SubmissionWizard/FieldContainer.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepOne.js
  site/gatsby-site/src/components/forms/Tags.js
  site/gatsby-site/src/components/forms/TagsInputGroup.js
  site/gatsby-site/src/components/forms/TextInputGroup.js
  site/gatsby-site/src/components/forms/Typeahead.js
  site/gatsby-site/src/components/incidents/IncidentEditModal.js
  site/gatsby-site/src/components/incidents/IncidentForm.js
  site/gatsby-site/src/components/incidents/IncidentIdField.js
  site/gatsby-site/src/components/incidents/IncidentsTable.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
  site/gatsby-site/src/pages/apps/incidents.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: PR:Needs Review

#1767 Fix description validation regex for submit form
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/src/components/forms/SubmissionWizard/StepThree.js
Labels: PR:Needs Review

#1774 Add toasts for errors on unsubscribe and confirmemail pages
  site/gatsby-site/cypress/e2e/integration/confirmemail.cy.js
  site/gatsby-site/cypress/e2e/integration/unsubscribe.cy.js
  site/gatsby-site/src/pages/confirmemail.js
  site/gatsby-site/src/pages/unsubscribe.js
Labels: PR:Mergeable

#1765 Remove bootstrap from variants page
  site/gatsby-site/cypress/e2e/incidentVariants.cy.js
  site/gatsby-site/cypress/e2e/integration/apps/variants.cy.js
  site/gatsby-site/i18n/locales/en/popovers.json
  site/gatsby-site/i18n/locales/es/popovers.json
  site/gatsby-site/i18n/locales/fr/popovers.json
  site/gatsby-site/src/components/forms/Label.js
  site/gatsby-site/src/components/forms/TextInputGroup.js
  site/gatsby-site/src/components/submissions/SubmissionReview.js
  site/gatsby-site/src/components/variants/VariantEditModal.js
  site/gatsby-site/src/components/variants/VariantForm.js
  site/gatsby-site/src/components/variants/VariantList.js
  site/gatsby-site/src/components/variants/VariantsTable.js
  site/gatsby-site/src/pages/apps/variants.js
  site/gatsby-site/src/tailwind.css
Labels: PR:Mergeable

#1772 Hide carousel arrows and navigation if it has just one item
  site/gatsby-site/src/components/cite/ImageCarousel.js
Labels: PR:Mergeable

#1771 Fix submission queue url overflow
  site/gatsby-site/src/components/submissions/SubmissionReview.js
Labels: PR:Needs Review

#1761 Remove styled components from TSNE page
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: PR:Needs Review

#1749 Remove bootstrap/styled components from discover page
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/src/components/discover/Actions.js
  site/gatsby-site/src/components/discover/ClearFilters.js
  site/gatsby-site/src/components/discover/DisplayModeSwitch.js
  site/gatsby-site/src/components/discover/Filter.js
  site/gatsby-site/src/components/discover/Filters.js
  site/gatsby-site/src/components/discover/Hits.js
  site/gatsby-site/src/components/discover/OptionsModal.js
  site/gatsby-site/src/components/discover/QuickAccess.js
  site/gatsby-site/src/components/discover/Stats.js
  site/gatsby-site/src/components/discover/filterTypes/RangeInput.js
  site/gatsby-site/src/components/discover/filterTypes/RefinementList.js
  site/gatsby-site/src/components/discover/hitTypes/Compact.js
  site/gatsby-site/src/components/discover/hitTypes/Details.js
  site/gatsby-site/src/components/discover/hitTypes/List.js
  site/gatsby-site/src/components/discover/hitTypes/shared.js
  site/gatsby-site/src/components/forms/SearchInput.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/tailwind.config.js
Labels: PR:Needs Review

#1776 Add improv ai blog post
  site/gatsby-site/blog/improv-ai/images/image1.png
  site/gatsby-site/blog/improv-ai/images/image2.png
  site/gatsby-site/blog/improv-ai/images/image3.png
  site/gatsby-site/blog/improv-ai/images/image4.png
  site/gatsby-site/blog/improv-ai/index.es.mdx
  site/gatsby-site/blog/improv-ai/index.fr.mdx
  site/gatsby-site/blog/improv-ai/index.mdx
  site/gatsby-site/src/components/ui/MdxComponents.js
Labels: PR:Needs Review

#1508 Fix tests for related reports
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/cypress/support/commands.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
Labels: PR:Needs Review

#1734 Always show report expanded on report's page
  site/gatsby-site/cypress/e2e/integration/report.cy.js
  site/gatsby-site/src/components/reports/ReportCard.js
  site/gatsby-site/src/templates/report.js
Labels: PR:Needs Review

#1758 Fix Incident variants test
  site/gatsby-site/cypress/e2e/incidentVariants.cy.js
Labels: PR:Needs Review

#1775 Fix/bootstrap wordcounts
  site/gatsby-site/src/components/Outline.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/src/components/styles/Docs.js
  site/gatsby-site/src/components/styles/Post.js
  site/gatsby-site/src/components/styles/Sidebar.js
  site/gatsby-site/src/pages/account.js
  site/gatsby-site/src/pages/apps/newsdigest.js
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/pages/blog/index.js
  site/gatsby-site/src/pages/summaries/flagged.js
  site/gatsby-site/src/pages/summaries/incidents.js
  site/gatsby-site/src/pages/summaries/leaderboard.js
  site/gatsby-site/src/pages/taxonomies.js
  site/gatsby-site/src/tailwind.css
  site/gatsby-site/src/templates/backups.js
  site/gatsby-site/src/templates/cite-duplicate.js
  site/gatsby-site/src/templates/doc.js
  site/gatsby-site/src/templates/entity.js
  site/gatsby-site/src/templates/post.js
  site/gatsby-site/src/templates/taxonomy.js
  site/gatsby-site/src/templates/tsneVisualizationPage.js
  site/gatsby-site/src/templates/wordcounts.js
Labels: PR:Needs Review

#1800 Fix/related report test
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
Labels: PR:Needs Review

#1790 Remove unused bootstrap Card from blog post
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.es.mdx
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.fr.mdx
  site/gatsby-site/blog/using-ai-to-connect-ai-incidents/index.mdx
Labels: PR:Mergeable

#1789 Move Rollbar Access Token to a Realm secret
  README.md
  site/gatsby-site/cypress/e2e/unit/functions/logRollbar.cy.js
  site/realm/functions/logRollbar.js
  site/realm/values/rollbarAccessToken.json
Labels: PR:Work Needed

#1751 Add dynamic Cite page for future Incidents
  site/gatsby-site/cypress/e2e/unit/pageCreators/createCitationPages.cy.js
  site/gatsby-site/src/graphql/incidents.js
  site/gatsby-site/src/pages/cite/[id].js
  site/gatsby-site/src/templates/cite.js
  site/gatsby-site/src/templates/citeTemplate.js
  site/gatsby-site/src/utils/cite.js
Labels: PR:Work Needed
