Repository responsible-ai-collaborative/aiid, pull requests merged in 2023-01, with the labels that each got.

#1514 Standardize New Incident and New Incident for Entity Emails
  site/gatsby-site/cypress/e2e/integration/apps/newsSearch.cy.js
  site/gatsby-site/cypress/e2e/unit/functions/processNotifications.cy.js
  site/gatsby-site/cypress/fixtures/candidates/newsArticles.json
  site/realm/functions/getEmailTemplateNewIncident.js
  site/realm/functions/processNotifications.js
Labels: PR:Needs Review

#1516 [HOTFIX] Skip `downloadIndex.cy.js` failing test
  site/gatsby-site/cypress/e2e/integration/downloadIndex.cy.js
Labels: PR:Needs Review

#1518 Use local names for languages in switcher
  site/gatsby-site/cypress/e2e/integration/languageSwitcher.cy.js
  site/gatsby-site/src/components/i18n/LanguageSwitcher.js
Labels: PR:Needs Review

#1520 Move process notifications to after deploy
  site/gatsby-site/netlify.toml
Labels: PR:Needs Review

#1509 Fix subscribe/unsubscribe test
  site/gatsby-site/cypress/e2e/integration/subscriptions.cy.js
Labels: PR:Mergeable

#1502 Fix Typeahead styling on /cite/edit
  site/gatsby-site/src/components/forms/IncidentReportForm.js
Labels: PR:Needs Review

#1483 Fix table entity filters
  site/gatsby-site/src/components/incidents/IncidentsTable.js
Labels: PR:Needs Review

#1484 Fix undefined in report edit toast link
  site/gatsby-site/src/pages/cite/edit.js
Labels: PR:Needs Review

#1461 Add subscriptions blog post
  site/gatsby-site/blog/user-story-spotlight-subscriptions-and-enewsletter/images/spotlight.png
  site/gatsby-site/blog/user-story-spotlight-subscriptions-and-enewsletter/index.es.mdx
  site/gatsby-site/blog/user-story-spotlight-subscriptions-and-enewsletter/index.fr.mdx
  site/gatsby-site/blog/user-story-spotlight-subscriptions-and-enewsletter/index.mdx
  site/gatsby-site/src/components/ui/MdxComponents.js
Labels: PR:Needs Review

#1390 Edit forms: Restore "fetch info," multi-line inputs
  site/gatsby-site/cypress/e2e/integration/apps/submitted.cy.js
  site/gatsby-site/src/components/forms/IncidentReportForm.js
  site/gatsby-site/src/components/forms/TextInputGroup.js
  site/gatsby-site/src/components/submissions/SubmissionForm.js
Labels: PR:Needs Review

#1528 Fix minified React error
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Needs Review

#1324 Feature/similar indicents cards
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/Layout.js
  site/gatsby-site/src/components/RelatedIncidents.js
  site/gatsby-site/src/components/RelatedIncidentsArea.js
  site/gatsby-site/src/components/SimilaritySelector.js
  site/gatsby-site/src/components/forms/SubmitForm.js
  site/gatsby-site/tailwind.config.js
Labels: PR:Mergeable

#1543 Avoid typing on date picker input
  site/gatsby-site/src/pages/summaries/incidentsOverTime.js
Labels: PR:Needs Review

#1541 Fix localized link on Similar Incidents section
  site/gatsby-site/cypress/e2e/integration/cite.cy.js
  site/gatsby-site/src/components/cite/SimilarIncidents.js
Labels: PR:Needs Review

#1503 SEO improvements
  site/gatsby-site/cypress/e2e/integration/submit.cy.js
  site/gatsby-site/cypress/e2e/unit/pageCreators/createCitationPages.cy.js
  site/gatsby-site/gatsby-node.js
  site/gatsby-site/netlify.toml
  site/gatsby-site/page-creators/createCitationPages.js
  site/gatsby-site/page-creators/createMdxPages.js
Labels: PR:Work Needed

#1547 Prevent gatsby i18n theme to duplicate pages
  site/gatsby-site/cypress/e2e/unit/pageCreators/createReportPages.cy.js
  site/gatsby-site/page-creators/createReportPages.js
Labels: PR:Mergeable

#1558 Add november blog post translations
  site/gatsby-site/blog/incident-report-2022-november/index.es.mdx
  site/gatsby-site/blog/incident-report-2022-november/index.fr.mdx
Labels: PR:Needs Review

#1559 Feature/header footer updates
  site/gatsby-site/config.js
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/src/components/layout/Footer.js
  site/gatsby-site/src/components/ui/Header.js
Labels: PR:Needs Review

#1561 Fix/french localization
  site/gatsby-site/gatsby-config.js
  site/gatsby-site/i18n/locales/en/footer.json
  site/gatsby-site/i18n/locales/es/entities.json
  site/gatsby-site/i18n/locales/es/footer.json
  site/gatsby-site/i18n/locales/es/translation.json
  site/gatsby-site/i18n/locales/fr/entities.json
  site/gatsby-site/i18n/locales/fr/footer.json
  site/gatsby-site/i18n/locales/fr/translation.json
  site/gatsby-site/src/components/cite/TsneVisualization.js
  site/gatsby-site/src/components/layout/Footer.js
  site/gatsby-site/src/templates/tsneVisualizationPage.js
Labels: PR:Needs Review

#1560 Fix/sidebar french title
  site/gatsby-site/i18n/locales/fr/translation.json
Labels: PR:Mergeable

#1562 Feature/translate blog posts
  site/gatsby-site/blog/incident-report-2022-december/index.es.mdx
  site/gatsby-site/blog/incident-report-2022-december/index.fr.mdx
  site/gatsby-site/blog/introducing-ai-incident-responses/index.es.mdx
  site/gatsby-site/blog/introducing-ai-incident-responses/index.fr.mdx
  site/gatsby-site/blog/user-story-spotlight-subscriptions-and-enewsletter/index.es.mdx
  site/gatsby-site/blog/user-story-spotlight-subscriptions-and-enewsletter/index.fr.mdx
Labels: PR:Needs Review

#1504 Feature/discover incident reports
  site/gatsby-site/cypress/e2e/integration/apps/newsSearch.cy.js
  site/gatsby-site/cypress/e2e/integration/discover.cy.js
  site/gatsby-site/src/components/discover/Hits.js
  site/gatsby-site/src/components/discover/hitTypes/Compact.js
  site/gatsby-site/src/components/discover/hitTypes/Details.js
  site/gatsby-site/src/components/discover/hitTypes/List.js
  site/gatsby-site/src/components/discover/hitTypes/shared.js
  site/gatsby-site/src/pages/apps/discover.js
  site/gatsby-site/src/utils/AlgoliaUpdater.js
  site/gatsby-site/src/utils/algoliaSettings.js
  site/gatsby-site/src/utils/discover.js
Labels: PR:Needs Review

#1500 Avoid notify new Variants
  site/gatsby-site/cypress/e2e/unit/functions/onIncidentUpdate.cy.js
  site/realm/functions/onIncidentUpdate.js
Labels: PR:Needs Review

#1564 Standardize date formatting
  site/gatsby-site/src/components/blog/PostPreview.js
  site/gatsby-site/src/components/landing/LatestIncidentReport.js
  site/gatsby-site/src/components/layout/Footer.js
  site/gatsby-site/src/pages/apps/newsSearch.js
  site/gatsby-site/src/pages/apps/reports.js
  site/gatsby-site/src/pages/summaries/incidentsOverTime.js
  site/gatsby-site/src/templates/post.js
Labels: PR:Mergeable
